import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import "../equipe-escalas.css";

type EventRow={id:string;title:string;description:string|null;event_date:string;starts_at:string|null;ends_at:string|null;location_name:string|null;address:string|null;status:string;city:string|null;state:string|null;public_token:string};
type Opening={id:string;event_id:string;title:string;slots:number;advertised_value:number|null};
type Collaborator={id:string;name:string;whatsapp:string;city:string|null;state:string|null;notes:string|null;network_status:string;calendar_token:string};
type CollaboratorJob={id:string;status:string;assigned_role:string|null;agreed_value:number|null;team_events:{title:string;event_date:string;starts_at:string|null;location_name:string|null;city:string|null}|null};
type Application={id:string;status:string;candidate_name:string;candidate_whatsapp:string;candidate_city:string|null;candidate_notes:string|null;assigned_role:string|null;agreed_value:number|null;attendance_status:string|null;attendance_responded_at:string|null;removed_from_scale_at?:string|null;removal_reason?:string|null;collaborator_id:string|null;opening_id:string;team_event_openings:{title:string}|null};

export const Route=createFileRoute("/equipe-escalas")({component:EquipeEscalasPage});

function EquipeEscalasPage(){
 const navigate=useNavigate();
 const [businessId,setBusinessId]=useState("");
 const [businessName,setBusinessName]=useState("");
 const [events,setEvents]=useState<EventRow[]>([]);
 const [people,setPeople]=useState<Collaborator[]>([]);
 const [loading,setLoading]=useState(true);
 const [creating,setCreating]=useState(false);
 const [selectedEventId,setSelectedEventId]=useState("");
 const [openings,setOpenings]=useState<Opening[]>([]);
 const [openingForm,setOpeningForm]=useState({title:"Recreador",slots:"1",advertised_value:""});
 const [applications,setApplications]=useState<Application[]>([]);
 const [assignment,setAssignment]=useState<Record<string,{role:string;value:string}>>({});
 const [selectedPerson,setSelectedPerson]=useState<Collaborator|null>(null);
 const [personJobs,setPersonJobs]=useState<CollaboratorJob[]>([]);
 const [dashboardStats,setDashboardStats]=useState({openSlots:0,pending:0,waiting:0,unavailable:0});
 const [manualPerson,setManualPerson]=useState({name:"",whatsapp:"",city:"",state:"",notes:""});
 const [editingEvent,setEditingEvent]=useState(false);
 const [eventEdit,setEventEdit]=useState({title:"",description:"",event_date:"",starts_at:"",ends_at:"",location_name:"",address:"",city:"",state:""});
 const [form,setForm]=useState({title:"",description:"",event_date:"",starts_at:"",ends_at:"",location_name:"",address:"",city:"",state:""});

 async function load(){
  const {data:{user}}=await supabase.auth.getUser();
  if(!user){navigate({to:"/entrar"});return}
  const {data:b}=await supabase.from("business_profiles").select("id,business_name").eq("owner_id",user.id).maybeSingle();
  if(!b){setLoading(false);return}
  setBusinessId(b.id);setBusinessName(b.business_name);
  const [{data:e},{data:p}]=await Promise.all([
   supabase.from("team_events").select("id,title,description,event_date,starts_at,ends_at,location_name,address,status,city,state,public_token").eq("business_id",b.id).order("event_date",{ascending:true}),
   supabase.from("team_collaborators").select("id,name,whatsapp,city,state,notes,network_status,calendar_token").eq("business_id",b.id).order("name")
  ]);
  setEvents((e||[]) as EventRow[]);setPeople((p||[]) as Collaborator[]);
  const activeIds=(e||[]).filter(x=>x.status!=="completed"&&x.status!=="cancelled").map(x=>x.id);
  if(activeIds.length){const [{data:allOpenings},{data:allApps}]=await Promise.all([supabase.from("team_event_openings").select("event_id,slots").in("event_id",activeIds),supabase.from("team_applications").select("event_id,status,attendance_status").in("event_id",activeIds)]);const slots=(allOpenings||[]).reduce((n,x)=>n+Number(x.slots||0),0);const confirmed=(allApps||[]).filter(x=>x.status==="confirmed").length;setDashboardStats({openSlots:Math.max(0,slots-confirmed),pending:(allApps||[]).filter(x=>x.status==="pending").length,waiting:(allApps||[]).filter(x=>x.status==="confirmed"&&!x.attendance_status).length,unavailable:(allApps||[]).filter(x=>x.status==="confirmed"&&x.attendance_status==="unavailable").length})}else setDashboardStats({openSlots:0,pending:0,waiting:0,unavailable:0});
  if(!selectedEventId&&e?.[0]?.id)setSelectedEventId(e[0].id); setLoading(false);
 }
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!selectedEventId){setOpenings([]);setApplications([]);return} void Promise.all([
 supabase.from("team_event_openings").select("id,event_id,title,slots,advertised_value").eq("event_id",selectedEventId).order("created_at"),
 supabase.from("team_applications").select("id,status,candidate_name,candidate_whatsapp,candidate_city,candidate_notes,assigned_role,agreed_value,attendance_status,attendance_responded_at,removed_from_scale_at,removal_reason,collaborator_id,opening_id,team_event_openings(title)").eq("event_id",selectedEventId).order("created_at",{ascending:false})
 ]).then(([o,a])=>{setOpenings((o.data||[]) as Opening[]);setApplications((a.data||[]) as unknown as Application[])})},[selectedEventId]);
 const upcoming=useMemo(()=>events.filter(e=>e.status!=="cancelled"&&e.status!=="completed"),[events]);

 async function addManualPerson(ev:FormEvent){ev.preventDefault();if(!businessId||!manualPerson.name.trim()||!manualPerson.whatsapp.trim())return;const {error}=await supabase.from("team_collaborators").insert({business_id:businessId,name:manualPerson.name.trim(),whatsapp:manualPerson.whatsapp.trim(),city:manualPerson.city.trim()||null,state:manualPerson.state.trim().toUpperCase()||null,notes:manualPerson.notes.trim()||null});if(error){alert(error.code==="23505"?"Este WhatsApp já está na sua rede.":error.message);return}setManualPerson({name:"",whatsapp:"",city:"",state:"",notes:""});await load()}
 function beginEventEdit(){if(!selectedEvent)return;setEventEdit({title:selectedEvent.title,description:selectedEvent.description||"",event_date:selectedEvent.event_date,starts_at:selectedEvent.starts_at?.slice(0,5)||"",ends_at:selectedEvent.ends_at?.slice(0,5)||"",location_name:selectedEvent.location_name||"",address:selectedEvent.address||"",city:selectedEvent.city||"",state:selectedEvent.state||""});setEditingEvent(true)}
 async function saveEventEdit(ev:FormEvent){ev.preventDefault();if(!selectedEventId)return;const {error}=await supabase.from("team_events").update({...eventEdit,starts_at:eventEdit.starts_at||null,ends_at:eventEdit.ends_at||null,updated_at:new Date().toISOString()}).eq("id",selectedEventId);if(error){alert(error.message);return}setEditingEvent(false);await load()}
 async function editOpening(o:Opening){const slots=window.prompt("Quantidade de vagas",String(o.slots));if(slots===null)return;const value=window.prompt("Valor anunciado (deixe vazio para valor a combinar)",o.advertised_value==null?"":String(o.advertised_value));if(value===null)return;const n=Number(slots);if(!Number.isInteger(n)||n<1){alert("Informe uma quantidade válida.");return}const {error}=await supabase.from("team_event_openings").update({slots:n,advertised_value:value.trim()===""?null:Number(value)}).eq("id",o.id);if(error){alert(error.message);return}const {data}=await supabase.from("team_event_openings").select("id,event_id,title,slots,advertised_value").eq("event_id",selectedEventId).order("created_at");setOpenings((data||[]) as Opening[]);await load()}
 async function createEvent(ev:FormEvent){
  ev.preventDefault(); if(!businessId||!form.title||!form.event_date)return;
  setCreating(true);
  const payload={business_id:businessId,...form,starts_at:form.starts_at||null,ends_at:form.ends_at||null,status:"draft"};
  const {error}=await supabase.from("team_events").insert(payload);
  setCreating(false);
  if(error){alert("Não foi possível criar o evento: "+error.message);return}
  setForm({title:"",description:"",event_date:"",starts_at:"",ends_at:"",location_name:"",address:"",city:"",state:""});
  await load();
 }
 async function addOpening(ev:FormEvent){ev.preventDefault();if(!selectedEventId)return;const {error}=await supabase.from("team_event_openings").insert({event_id:selectedEventId,title:openingForm.title.trim(),slots:Number(openingForm.slots),advertised_value:openingForm.advertised_value?Number(openingForm.advertised_value):null});if(error){alert(error.message);return}const {data}=await supabase.from("team_event_openings").select("id,event_id,title,slots,advertised_value").eq("event_id",selectedEventId).order("created_at");setOpenings((data||[]) as Opening[]);setOpeningForm({title:"Recreador",slots:"1",advertised_value:""})}
 async function publishEvent(){if(!selectedEventId||!openings.length){alert("Adicione pelo menos uma vaga antes de publicar.");return}const {error}=await supabase.from("team_events").update({status:"open"}).eq("id",selectedEventId);if(error){alert(error.message);return}await load()}
 async function copyPublicLink(){const e=events.find(x=>x.id===selectedEventId);if(!e)return;const link=`${window.location.origin}/oportunidade/${e.public_token}`;await navigator.clipboard.writeText(link);alert("Link de candidatura copiado.")}
 async function manageApplication(id:string,action:"approve"|"reject"|"confirm"){const values=assignment[id];const {error}=await supabase.rpc("manage_team_application",{p_application_id:id,p_action:action,p_assigned_role:values?.role||null,p_agreed_value:values?.value?Number(values.value):null});if(error){alert(error.message);return}await load();const {data}=await supabase.from("team_applications").select("id,status,candidate_name,candidate_whatsapp,candidate_city,candidate_notes,assigned_role,agreed_value,attendance_status,attendance_responded_at,removed_from_scale_at,removal_reason,collaborator_id,opening_id,team_event_openings(title)").eq("event_id",selectedEventId).order("created_at",{ascending:false});setApplications((data||[]) as unknown as Application[])}
 function openWhatsApp(phone:string,name:string){const n=phone.replace(/\D/g,"");window.open(`https://wa.me/${n}?text=${encodeURIComponent(`Olá, ${name}! Estou entrando em contato sobre sua candidatura pelo LOSI Conecta.`)}`,"_blank","noopener,noreferrer")}
 async function copyCalendar(collaboratorId:string|null){const p=people.find(x=>x.id===collaboratorId);if(!p)return;await navigator.clipboard.writeText(`${window.location.origin}/calendario/${p.calendar_token}`);alert("Link exclusivo do Calendário copiado.")}
 async function openPerson(person:Collaborator){setSelectedPerson(person);const {data}=await supabase.from("team_applications").select("id,status,assigned_role,agreed_value,team_events(title,event_date,starts_at,location_name,city)").eq("collaborator_id",person.id).in("status",["approved","confirmed"]).order("created_at",{ascending:false});setPersonJobs((data||[]) as unknown as CollaboratorJob[])}
 async function togglePerson(){if(!selectedPerson)return;const next=selectedPerson.network_status==="active"?"inactive":"active";const {error}=await supabase.from("team_collaborators").update({network_status:next}).eq("id",selectedPerson.id);if(error){alert(error.message);return}setSelectedPerson({...selectedPerson,network_status:next});await load()}
 async function copyPersonCalendar(){if(!selectedPerson)return;await navigator.clipboard.writeText(`${window.location.origin}/calendario/${selectedPerson.calendar_token}`);alert("Link exclusivo do Calendário copiado.")}
 const officialScale=useMemo(()=>openings.map(opening=>{const assigned=applications.filter(a=>a.status==="confirmed"&&(a.assigned_role||"").trim().toLocaleLowerCase("pt-BR")===opening.title.trim().toLocaleLowerCase("pt-BR"));return {...opening,assigned,filled:assigned.length,remaining:Math.max(0,opening.slots-assigned.length),over:Math.max(0,assigned.length-opening.slots)}}),[openings,applications]);
 const scaleTotals=useMemo(()=>({slots:openings.reduce((n,o)=>n+o.slots,0),filled:applications.filter(a=>a.status==="confirmed").length,confirmed:applications.filter(a=>a.status==="confirmed"&&a.attendance_status==="confirmed").length,unavailable:applications.filter(a=>a.status==="confirmed"&&a.attendance_status==="unavailable").length}),[openings,applications]);
 async function refreshApplications(){const {data}=await supabase.from("team_applications").select("id,status,candidate_name,candidate_whatsapp,candidate_city,candidate_notes,assigned_role,agreed_value,attendance_status,attendance_responded_at,removed_from_scale_at,removal_reason,collaborator_id,opening_id,team_event_openings(title)").eq("event_id",selectedEventId).order("created_at",{ascending:false});setApplications((data||[]) as unknown as Application[])}
 async function removeFromScale(person:Application){const reason=person.attendance_status==="unavailable"?"Colaborador informou indisponibilidade":"Retirado da escala pelo fornecedor";if(!window.confirm(`Retirar ${person.candidate_name} da escala? A vaga será reaberta e o histórico será preservado.`))return;const {error}=await supabase.from("team_applications").update({status:"removed",removed_from_scale_at:new Date().toISOString(),removal_reason:reason}).eq("id",person.id).eq("status","confirmed");if(error){alert(error.message);return}await refreshApplications()}
 async function completeEvent(){if(!selectedEventId)return;if(!window.confirm("Encerrar este evento? A escala ficará preservada no histórico."))return;const {error}=await supabase.from("team_events").update({status:"completed",updated_at:new Date().toISOString()}).eq("id",selectedEventId);if(error){alert(error.message);return}setSelectedEventId("");await load()}
 const selectedEvent=events.find(e=>e.id===selectedEventId);
 if(loading)return <main className="team-page team-loading">Carregando Equipe & Escalas...</main>;
 return <main className="team-page">
  <header className="team-topbar"><button onClick={()=>navigate({to:"/painel"})}>← Painel</button><div><span>LOSI CONECTA</span><strong>Equipe & Escalas</strong></div></header>
  <section className="team-hero"><div><span>OPERAÇÃO PROFISSIONAL</span><h1>Sua rede. Seus eventos. Sua escala.</h1><p>Organize colaboradores em rede, publique oportunidades e monte cada escala mantendo função e valor final sob seu controle.</p></div><strong>{businessName}</strong></section>
  <section className="team-dashboard"><div className="team-dashboard-title"><div><span>VISÃO OPERACIONAL</span><h2>O que precisa da sua atenção</h2></div><p>Resumo dos eventos ativos e da sua equipe.</p></div><div className="team-dashboard-cards"><article><small>EVENTOS ATIVOS</small><strong>{upcoming.length}</strong><span>Próximas operações</span></article><article className={dashboardStats.openSlots?"attention":""}><small>POSIÇÕES EM ABERTO</small><strong>{dashboardStats.openSlots}</strong><span>Ainda precisam ser preenchidas</span></article><article className={dashboardStats.pending?"attention":""}><small>CANDIDATURAS PENDENTES</small><strong>{dashboardStats.pending}</strong><span>Aguardando sua análise</span></article><article className={dashboardStats.waiting?"attention":""}><small>AGUARDANDO PRESENÇA</small><strong>{dashboardStats.waiting}</strong><span>Sem resposta no calendário</span></article><article className={dashboardStats.unavailable?"danger":""}><small>NÃO PODEM COMPARECER</small><strong>{dashboardStats.unavailable}</strong><span>Exigem ajuste na escala</span></article></div></section>
  <section className="team-section"><div className="team-section-head"><div><span>MINHA EQUIPE</span><h2>Rede de colaboradores</h2></div><b>{people.length} na rede</b></div>
   <form className="team-manual-person" onSubmit={addManualPerson}><div><strong>Adicionar colaborador diretamente</strong><small>Para pessoas que já fazem parte da sua equipe ou rede.</small></div><input required placeholder="Nome" value={manualPerson.name} onChange={e=>setManualPerson({...manualPerson,name:e.target.value})}/><input required placeholder="WhatsApp" value={manualPerson.whatsapp} onChange={e=>setManualPerson({...manualPerson,whatsapp:e.target.value})}/><input placeholder="Cidade" value={manualPerson.city} onChange={e=>setManualPerson({...manualPerson,city:e.target.value})}/><input maxLength={2} placeholder="UF" value={manualPerson.state} onChange={e=>setManualPerson({...manualPerson,state:e.target.value.toUpperCase()})}/><button className="team-secondary">ADICIONAR À REDE</button></form>
   <div className="team-flow"><div className="team-flow-owner"><small>FORNECEDOR</small><strong>{businessName||"Sua empresa"}</strong></div><div className="team-flow-line"/><div className="team-flow-people">{people.length?people.map(p=><article key={p.id} role="button" tabIndex={0} onClick={()=>void openPerson(p)} onKeyDown={e=>{if(e.key==="Enter")void openPerson(p)}} className={p.network_status!=="active"?"inactive":""}><span>{p.name.slice(0,1).toUpperCase()}</span><strong>{p.name}</strong><small>{p.city||"Cidade não informada"}</small></article>):<div className="team-empty">Sua rede começa aqui. Os candidatos aprovados aparecerão neste fluxograma.</div>}</div></div>
  </section>
  {selectedPerson&&<div className="team-person-overlay" onClick={()=>setSelectedPerson(null)}><section className="team-person-panel" onClick={e=>e.stopPropagation()}><header><div><span>COLABORADOR DA REDE</span><h2>{selectedPerson.name}</h2><p>{selectedPerson.city||"Cidade não informada"}{selectedPerson.state?` · ${selectedPerson.state}`:""}</p></div><button onClick={()=>setSelectedPerson(null)} aria-label="Fechar">×</button></header>
   <div className="team-person-contact"><div><small>WHATSAPP</small><strong>{selectedPerson.whatsapp}</strong></div><button className="team-secondary" onClick={()=>openWhatsApp(selectedPerson.whatsapp,selectedPerson.name)}>CHAMAR NO WHATSAPP</button></div>
   {selectedPerson.notes&&<div className="team-person-notes"><small>ANOTAÇÕES / APRESENTAÇÃO</small><p>{selectedPerson.notes}</p></div>}
   <div className="team-person-actions"><button className="team-primary" onClick={copyPersonCalendar}>COPIAR LINK DO CALENDÁRIO</button><button className="team-secondary" onClick={togglePerson}>{selectedPerson.network_status==="active"?"DESATIVAR DA REDE":"REATIVAR NA REDE"}</button></div>
   <div className="team-person-history"><span>HISTÓRICO COM O FORNECEDOR</span><h3>Datas e trabalhos</h3>{personJobs.length?personJobs.map(j=><article key={j.id}><time>{j.team_events?new Date(j.team_events.event_date+"T12:00:00").toLocaleDateString("pt-BR"):"—"}</time><div><strong>{j.team_events?.title||"Evento"}</strong><small>{j.assigned_role||"Função ainda não definida"} · {j.team_events?.location_name||j.team_events?.city||"Local a definir"}</small></div><b>{j.agreed_value!=null?Number(j.agreed_value).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):j.status==="approved"?"Em conversa":"Valor não informado"}</b></article>):<div className="team-empty">Nenhum trabalho registrado ainda.</div>}</div>
  </section></div>}
  <section className="team-grid">
   <div className="team-section"><div className="team-section-head"><div><span>ESCALAS</span><h2>Próximos eventos</h2></div><b>{upcoming.length}</b></div>
    <div className="team-events">{upcoming.length?upcoming.map(e=><article key={e.id} className={selectedEventId===e.id?"selected":""} onClick={()=>setSelectedEventId(e.id)}><time>{new Date(e.event_date+"T12:00:00").toLocaleDateString("pt-BR")}</time><div><strong>{e.title}</strong><small>{e.city||"Local a definir"} · {e.status==="draft"?"Rascunho":e.status}</small></div></article>):<div className="team-empty">Nenhum evento criado ainda.</div>}</div>
    {events.some(e=>e.status==="completed")&&<div className="team-event-history"><span>HISTÓRICO</span>{events.filter(e=>e.status==="completed").map(e=><article key={e.id} onClick={()=>setSelectedEventId(e.id)}><time>{new Date(e.event_date+"T12:00:00").toLocaleDateString("pt-BR")}</time><div><strong>{e.title}</strong><small>Evento concluído · {e.city||"Local não informado"}</small></div></article>)}</div>}
   </div>
   {selectedEvent&&<div className="team-section team-opening-manager"><div className="team-section-head"><div><span>VAGAS DO EVENTO</span><h2>{selectedEvent.title}</h2></div><div className="team-head-actions"><b>{selectedEvent.status==="open"?"Publicado":selectedEvent.status==="completed"?"Concluído":"Rascunho"}</b>{selectedEvent.status!=="completed"&&<button className="team-edit-link" onClick={beginEventEdit}>EDITAR EVENTO</button>}</div></div>{editingEvent&&<form className="team-event-edit" onSubmit={saveEventEdit}><input required value={eventEdit.title} onChange={e=>setEventEdit({...eventEdit,title:e.target.value})}/><textarea value={eventEdit.description} onChange={e=>setEventEdit({...eventEdit,description:e.target.value})}/><div><input required type="date" value={eventEdit.event_date} onChange={e=>setEventEdit({...eventEdit,event_date:e.target.value})}/><input type="time" value={eventEdit.starts_at} onChange={e=>setEventEdit({...eventEdit,starts_at:e.target.value})}/><input type="time" value={eventEdit.ends_at} onChange={e=>setEventEdit({...eventEdit,ends_at:e.target.value})}/></div><input placeholder="Local" value={eventEdit.location_name} onChange={e=>setEventEdit({...eventEdit,location_name:e.target.value})}/><input placeholder="Endereço" value={eventEdit.address} onChange={e=>setEventEdit({...eventEdit,address:e.target.value})}/><div><input placeholder="Cidade" value={eventEdit.city} onChange={e=>setEventEdit({...eventEdit,city:e.target.value})}/><input maxLength={2} placeholder="UF" value={eventEdit.state} onChange={e=>setEventEdit({...eventEdit,state:e.target.value.toUpperCase()})}/></div><div><button className="team-primary">SALVAR ALTERAÇÕES</button><button type="button" className="team-secondary" onClick={()=>setEditingEvent(false)}>CANCELAR</button></div></form>}
    <div className="team-opening-list">{openings.map(o=><article key={o.id}><div><strong>{o.title}</strong><small>{o.slots} {o.slots===1?"vaga":"vagas"}</small></div><b>{o.advertised_value!=null?o.advertised_value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):"Valor a combinar"}</b>{selectedEvent.status!=="completed"&&<button className="team-edit-opening" onClick={()=>void editOpening(o)}>EDITAR</button>}</article>)}</div>
    <form className="team-opening-form" onSubmit={addOpening}><label>Vaga<select value={openingForm.title} onChange={e=>setOpeningForm({...openingForm,title:e.target.value})}><option>Apoio</option><option>Monitor</option><option>Recreador</option><option>Coordenador</option><option>Outro</option></select></label><label>Quantidade<input type="number" min="1" required value={openingForm.slots} onChange={e=>setOpeningForm({...openingForm,slots:e.target.value})}/></label><label>Valor anunciado<input type="number" min="0" step="0.01" value={openingForm.advertised_value} onChange={e=>setOpeningForm({...openingForm,advertised_value:e.target.value})} placeholder="R$"/></label><button className="team-secondary">ADICIONAR VAGA</button></form>
    <div className="team-publish-actions"><button className="team-primary" onClick={publishEvent} disabled={selectedEvent.status==="open"}>{selectedEvent.status==="open"?"OPORTUNIDADE PUBLICADA":"PUBLICAR OPORTUNIDADE"}</button>{selectedEvent.status==="open"&&<button className="team-secondary" onClick={copyPublicLink}>COPIAR LINK DE CANDIDATURA</button>}{selectedEvent.status==="open"&&<button className="team-secondary team-complete-event" onClick={completeEvent}>ENCERRAR EVENTO</button>}</div>
   </div>}
   {selectedEvent&&<section className="team-section official-scale"><div className="team-section-head"><div><span>ESCALA OFICIAL</span><h2>Equipe do evento</h2></div><b>{scaleTotals.filled}/{scaleTotals.slots} posições</b></div><div className="scale-summary"><div><small>POSIÇÕES</small><strong>{scaleTotals.slots}</strong></div><div><small>NA ESCALA</small><strong>{scaleTotals.filled}</strong></div><div><small>PRESENÇA CONFIRMADA</small><strong>{scaleTotals.confirmed}</strong></div><div><small>NÃO PODE</small><strong>{scaleTotals.unavailable}</strong></div></div><div className="scale-roles">{officialScale.length?officialScale.map(role=><article key={role.id} className={role.over?"overbooked":""}><header><div><strong>{role.title}</strong><small>{role.filled} de {role.slots} preenchidas</small></div><b>{role.over?role.over+" acima da quantidade":role.remaining?role.remaining+" "+(role.remaining===1?"vaga aberta":"vagas abertas"):"Completo"}</b></header><div className="scale-members">{role.assigned.length?role.assigned.map(person=><div key={person.id}><span>{person.candidate_name.slice(0,1).toUpperCase()}</span><div><strong>{person.candidate_name}</strong><small>{person.agreed_value!=null?person.agreed_value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):"Valor não informado"}</small></div><em className={"attendance-"+(person.attendance_status||"waiting")}>{person.attendance_status==="confirmed"?"Confirmou":person.attendance_status==="unavailable"?"Não pode":"Aguardando"}</em>{person.attendance_status==="unavailable"&&<button className="scale-remove" onClick={()=>void removeFromScale(person)}>RETIRAR</button>}</div>):<div className="scale-empty-role">Nenhum colaborador confirmado nesta função.</div>}</div></article>):<div className="team-empty">Cadastre as vagas do evento para montar a escala oficial.</div>}</div></section>}
   {selectedEvent&&<section className="team-section team-candidates"><div className="team-section-head"><div><span>CANDIDATOS</span><h2>Central de candidaturas</h2></div><b>{applications.length} recebidas</b></div>
    <div className="team-candidate-list">{applications.length?applications.map(a=><article key={a.id}><div className="team-candidate-main"><span>{a.candidate_name.slice(0,1).toUpperCase()}</span><div><strong>{a.candidate_name}</strong><small>{a.team_event_openings?.title||"Vaga"} · {a.candidate_city||"Cidade não informada"}</small><small>{a.candidate_whatsapp}</small></div><b className={`status-${a.status}`}>{a.status==="pending"?"Pendente":a.status==="approved"?"Aprovado":a.status==="rejected"?"Recusado":"Confirmado"}</b></div>{a.candidate_notes&&<p>{a.candidate_notes}</p>}
     {a.status==="pending"&&<div className="team-candidate-actions"><button className="team-primary" onClick={()=>void manageApplication(a.id,"approve")}>APROVAR E ADICIONAR À REDE</button><button className="team-secondary" onClick={()=>void manageApplication(a.id,"reject")}>RECUSAR</button></div>}
     {a.status==="approved"&&<><div className="team-candidate-actions"><button className="team-secondary" onClick={()=>openWhatsApp(a.candidate_whatsapp,a.candidate_name)}>CONVERSAR NO WHATSAPP</button><button className="team-secondary" onClick={()=>void copyCalendar(a.collaborator_id)}>COPIAR CALENDÁRIO</button></div><div className="team-assignment"><label>Função final<input value={assignment[a.id]?.role||""} onChange={e=>setAssignment({...assignment,[a.id]:{role:e.target.value,value:assignment[a.id]?.value||""}})} placeholder="Ex.: Recreador"/></label><label>Valor acordado<input type="number" min="0" step=".01" value={assignment[a.id]?.value||""} onChange={e=>setAssignment({...assignment,[a.id]:{role:assignment[a.id]?.role||"",value:e.target.value}})} placeholder="R$"/></label><button className="team-primary" onClick={()=>void manageApplication(a.id,"confirm")}>CONFIRMAR NA ESCALA</button></div></>}
     {a.status==="confirmed"&&<div className="team-confirmed-row"><strong>{a.assigned_role}</strong><span>{a.agreed_value!=null?a.agreed_value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):"Valor não registrado"}</span><em className={`attendance-${a.attendance_status||"waiting"}`}>{a.attendance_status==="confirmed"?"PRESENÇA CONFIRMADA":a.attendance_status==="unavailable"?"NÃO PODE COMPARECER":"AGUARDANDO RESPOSTA"}</em><button className="team-secondary" onClick={()=>void copyCalendar(a.collaborator_id)}>COPIAR CALENDÁRIO</button></div>}</article>):<div className="team-empty">As candidaturas enviadas pelo link aparecerão aqui.</div>}</div>
   </section>}
   <form className="team-section team-form" onSubmit={createEvent}><div className="team-section-head"><div><span>NOVA ESCALA</span><h2>Criar evento</h2></div></div>
    <label>Nome do evento<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: Festa infantil — Aniversário da Laura"/></label>
    <label>Descrição<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descreva o evento, orientações e informações importantes."/></label>
    <div className="team-form-row"><label>Data<input required type="date" value={form.event_date} onChange={e=>setForm({...form,event_date:e.target.value})}/></label><label>Início<input type="time" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>Fim<input type="time" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label></div>
    <label>Local<input value={form.location_name} onChange={e=>setForm({...form,location_name:e.target.value})} placeholder="Ex.: Espaço Jardim"/></label>
    <label>Endereço<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label>
    <div className="team-form-row"><label>Cidade<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>UF<input maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})}/></label></div>
    <button className="team-primary" disabled={creating}>{creating?"CRIANDO...":"CRIAR EVENTO"}</button>
    <small className="team-form-note">Depois de criar o evento, as vagas (Apoio, Monitor, Recreador, Coordenador etc.) e seus valores anunciados serão adicionadas à escala.</small>
   </form>
  </section>
 </main>
}