import { createFileRoute } from "@tanstack/react-router";
import { FormEvent, useEffect, useState } from "react";
import "../equipe-escalas.css";
type Opening={id:string;title:string;slots:number;advertised_value:number|null};
type PublicEvent={title:string;description:string|null;event_date:string;starts_at:string|null;ends_at:string|null;location_name:string|null;address:string|null;city:string|null;state:string|null;business_profiles:{business_name:string}|null};
export const Route=createFileRoute("/oportunidade/$token")({component:OpportunityPage});
function OpportunityPage(){
 const {token}=Route.useParams();const [event,setEvent]=useState<PublicEvent|null>(null);const [openings,setOpenings]=useState<Opening[]>([]);const [loading,setLoading]=useState(true);const [sent,setSent]=useState(false);const [error,setError]=useState("");const [form,setForm]=useState({name:"",whatsapp:"",city:"",state:"",openingId:"",notes:""});
 async function call(body:Record<string,unknown>){const r=await fetch("https://bpvaftobiosjesdbaany.supabase.co/functions/v1/team-public-opportunity",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,...body})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível continuar.");return d}
 useEffect(()=>{void call({action:"get"}).then(d=>{setEvent(d.event);setOpenings(d.openings);if(d.openings[0])setForm(f=>({...f,openingId:d.openings[0].id}))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await call({action:"apply",...form});setSent(true)}catch(err){setError(err instanceof Error?err.message:"Não foi possível enviar.")}}
 if(loading)return <main className="opportunity-page"><div className="opportunity-card">Carregando oportunidade...</div></main>;
 if(!event)return <main className="opportunity-page"><div className="opportunity-card"><h1>Oportunidade indisponível</h1><p>{error}</p></div></main>;
 return <main className="opportunity-page"><section className="opportunity-card"><div className="opportunity-brand">LOSI <b>CONECTA</b></div><span className="opportunity-kicker">OPORTUNIDADE DE TRABALHO</span><h1>{event.title}</h1><p className="opportunity-company">{event.business_profiles?.business_name}</p><p>{event.description}</p><div className="opportunity-meta"><div><small>DATA</small><strong>{new Date(event.event_date+"T12:00:00").toLocaleDateString("pt-BR")}</strong></div><div><small>HORÁRIO</small><strong>{event.starts_at?.slice(0,5)||"A definir"} {event.ends_at&&"– "+event.ends_at.slice(0,5)}</strong></div><div><small>LOCAL</small><strong>{event.location_name||event.city||"A definir"}</strong></div></div>
 <div className="opportunity-openings">{openings.map(o=><article key={o.id}><div><strong>{o.title}</strong><small>{o.slots} {o.slots===1?"vaga":"vagas"}</small></div><b>{o.advertised_value!=null?o.advertised_value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):"A combinar"}</b></article>)}</div>
 {sent?<div className="opportunity-success"><strong>Candidatura enviada!</strong><p>O fornecedor recebeu seus dados. Caso você seja aprovado, ele entrará em contato e poderá adicionar você à rede de colaboradores.</p></div>:<form className="opportunity-form" onSubmit={submit}><h2>Quero me candidatar</h2><label>Nome completo<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>WhatsApp<input required inputMode="tel" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></label><div><label>Cidade<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>UF<input maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})}/></label></div><label>Vaga de interesse<select required value={form.openingId} onChange={e=>setForm({...form,openingId:e.target.value})}>{openings.map(o=><option key={o.id} value={o.id}>{o.title}{o.advertised_value!=null?" · "+o.advertised_value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):""}</option>)}</select></label><label>Conte um pouco sobre você<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<p className="opportunity-error">{error}</p>}<button>ENVIAR CANDIDATURA</button><small>Ao enviar, seus dados serão compartilhados com o fornecedor responsável por esta oportunidade.</small></form>}</section></main>
}