import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import "../receipts.css";

export const Route = createFileRoute("/recibos-recebidos")({ component: ReceivedReceiptsPage });
const APP_ORIGIN = typeof window !== "undefined" ? window.location.origin : "https://losi-conecta-oficial.vercel.app";

type Request={id:string;public_token:string;status:string;created_at:string;submitted_at:string|null};
type Receipt={id:string;request_id:string;issuer_name:string;issuer_document:string|null;issuer_phone:string|null;service:string;service_date:string|null;amount_cents:number;payment_method:string|null;created_at:string};

const money=(v:number)=>(v/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

function ReceivedReceiptsPage(){
  const navigate=useNavigate(); const [user,setUser]=useState<string|null>(null),[requests,setRequests]=useState<Request[]>([]),[receipts,setReceipts]=useState<Record<string,Receipt>>({}),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  useEffect(()=>{(async()=>{const {data}=await supabase.auth.getSession();if(!data.session){navigate({to:"/entrar"});return}setUser(data.session.user.id);const {data:rs,error}=await supabase.from("receipt_requests").select("id,public_token,status,created_at,submitted_at").eq("requester_user_id",data.session.user.id).order("created_at",{ascending:false});if(error){setMessage("Não foi possível carregar as solicitações.");setLoading(false);return}setRequests((rs||[]) as Request[]);if(rs?.length){const {data:rc}=await supabase.from("received_receipts").select("id,request_id,issuer_name,issuer_document,issuer_phone,service,service_date,amount_cents,payment_method,created_at").eq("requester_user_id",data.session.user.id);const map:Record<string,Receipt>={};(rc||[]).forEach((x)=>{map[x.request_id]=x as Receipt});setReceipts(map)}setLoading(false)})()},[navigate]);
  async function createRequest(){if(!user)return;setMessage("");const token=crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");const {data,error}=await supabase.from("receipt_requests").insert({requester_user_id:user,public_token:token}).select("id,public_token,status,created_at,submitted_at").single();if(error){setMessage("Não foi possível criar o link.");return}setRequests(v=>[data as Request,...v]);setMessage("Link criado. Copie e envie pelo WhatsApp.");}
  function share(r:Request){const url=APP_ORIGIN+"/emitir-recibo/"+r.public_token;if(navigator.share)navigator.share({title:"Emitir recibo — LOSI CONECTA",text:"Use este link para emitir seu recibo:",url}).catch(()=>{});else navigator.clipboard?.writeText(url).then(()=>setMessage("Link copiado para a área de transferência."));}
  if(loading)return <main className="receipts-state">Carregando recibos recebidos...</main>;
  return <main className="dashboard-page receipts-page"><aside className="dashboard-sidebar receipts-sidebar"><div className="dashboard-sidebar-brand"><span>LOSI</span><strong>CONECTA</strong></div><div className="dashboard-sidebar-caption">PAINEL PROFISSIONAL</div><nav className="dashboard-sidebar-nav"><Link to="/painel" className="dashboard-nav-item"><span className="dashboard-nav-mark">01</span><span><strong>Visão geral</strong><small>Resumo da conta</small></span></Link><Link to="/recibos" className="dashboard-nav-item active"><span className="dashboard-nav-mark">07</span><span><strong>Recibos</strong><small>Emitir e receber</small></span></Link></nav><div className="dashboard-sidebar-footer"><Link to="/painel" className="dashboard-sidebar-logout">Voltar ao painel</Link></div></aside>
  <div className="dashboard-main"><header className="dashboard-header receipts-header"><div className="dashboard-header-context"><span>DOCUMENTOS PROFISSIONAIS</span><strong>Recibos recebidos</strong></div><Link to="/recibos" className="dashboard-secondary receipts-back">Voltar para Recibos</Link></header>
  <section className="dashboard-content receipts-content"><div className="receipts-hero"><div><div className="dashboard-badge">RECIBOS RECEBIDOS</div><h1>Solicite recibos a quem você contratou</h1><p>Crie um link, envie para o prestador e receba o documento diretamente no seu painel. Ele não precisa ter cadastro.</p></div><div className="receipts-hero-mark"><span>LOSI</span><strong>CONECTA</strong><small>ENVIO SEM CADASTRO</small></div></div>
  {message&&<div className="receipts-message">{message}</div>}
  <section className="receipts-form-card"><div className="receipts-card-head"><div><span className="receipts-kicker">NOVA SOLICITAÇÃO</span><h2>Gerar link para o prestador</h2></div><button className="receipts-primary receipts-inline-action" onClick={createRequest}>+ Criar link</button></div><p className="receipts-note receipts-left-note">Cada link é individual e pode ser enviado diretamente pelo WhatsApp.</p></section>
  <section className="receipts-history-card"><div className="receipts-card-head"><div><span className="receipts-kicker">HISTÓRICO</span><h2>Solicitações de recibo</h2></div><span className="receipts-count">{requests.length}</span></div>{!requests.length?<div className="receipts-empty"><strong>Nenhuma solicitação criada</strong><span>Crie um link para começar.</span></div>:<div className="receipts-history-list">{requests.map(r=>{const x=receipts[r.id];const url=APP_ORIGIN+"/emitir-recibo/"+r.public_token;return <article key={r.id}><div><strong>{x?.issuer_name||"Aguardando prestador"}</strong><span>{x?.service||"Link enviado — aguardando preenchimento"}</span></div><div className="receipts-history-meta">{x&&<b>{money(x.amount_cents)}</b>}<span>{r.status==="submitted"?"Recebido":"Aguardando"}</span>{x?<button type="button" onClick={()=>{window.open(url,"_blank")}}>Abrir recibo</button>:<button type="button" onClick={()=>share(r)}>Compartilhar link</button>}</div></article>})}</div>}</section>
  </section></div></main>;
}