begin;
do $$ declare a uuid;b uuid;t uuid;g uuid:=gen_random_uuid();m uuid:=gen_random_uuid();r uuid:=gen_random_uuid();r2 uuid:=gen_random_uuid();gm uuid:=gen_random_uuid();gr uuid:=gen_random_uuid();result jsonb;start_balance bigint;up uuid:=gen_random_uuid();mr uuid:=gen_random_uuid();begin
 select x.user_id into a from public.losi_chat_accounts x join public.business_profiles b on b.id=x.business_id join public.profiles p on p.id=x.user_id where x.digital_number is not null and b.active and not coalesce(p.blocked,false) limit 1;
 select x.user_id into b from public.losi_chat_accounts x join public.business_profiles p on p.id=x.business_id join public.profiles u on u.id=x.user_id where x.user_id<>a and x.digital_number is not null and p.active and not coalesce(u.blocked,false) limit 1;
 if a is null or b is null then raise exception 'Duas contas ativas são necessárias';end if;
 update public.losi_chat_accounts set balance=greatest(balance,10) where user_id=b;
 select balance into start_balance from public.losi_chat_accounts where user_id=b;
 select id into t from public.losi_chat_threads where user_a=least(a,b) and user_b=greatest(a,b);
 if t is null then t:=gen_random_uuid();insert into public.losi_chat_threads(id,user_a,user_b) values(t,least(a,b),greatest(a,b));end if;
 insert into public.losi_chat_messages(id,thread_id,sender_id,body,created_at) values(m,t,a,'Original privada',clock_timestamp());
 result:=public.losi_chat_send_reply(b,t,false,r,'Minha resposta',m);
 if result->'message'->>'reply_to'<>m::text then raise exception 'Referência ausente';end if;
 perform public.losi_chat_send_reply(b,t,false,r,'Minha resposta',m);
 if (select balance from public.losi_chat_accounts where user_id=b)<>start_balance-1 then raise exception 'Resposta cobrada duas vezes';end if;
 if public.losi_chat_reply_previews(a,array[r])->r::text->>'text'<>'Original privada' then raise exception 'Citação ausente';end if;
 if public.losi_chat_reply_previews(gen_random_uuid(),array[r])<>'{}'::jsonb then raise exception 'Citação vazou para terceiro';end if;
 insert into public.losi_chat_hidden_messages(user_id,message_id) values(a,m);
 if public.losi_chat_reply_previews(a,array[r])->r::text->>'unavailable'<>'true' then raise exception 'Original oculta vazou';end if;
 update public.losi_chat_messages set deleted_at=clock_timestamp() where id=m;
 if public.losi_chat_reply_previews(b,array[r])->r::text->>'unavailable'<>'true' then raise exception 'Original excluída vazou';end if;
 begin perform public.losi_chat_send_reply(b,t,false,r2,'Inválida',m);raise exception 'Aceitou original excluída';exception when others then if sqlerrm<>'RESPOSTA_INVALIDA' then raise;end if;end;
 if (select balance from public.losi_chat_accounts where user_id=b)<>start_balance-1 then raise exception 'Falha descontou créditos';end if;
 insert into public.losi_chat_groups(id,owner_id,creator_id,name) values(g,a,a,'Grupo teste');
 insert into public.losi_chat_group_members(group_id,user_id) values(g,a),(g,b);
 insert into public.losi_chat_messages(id,group_id,sender_id,body,created_at) values(gm,g,a,'Mensagem do grupo',clock_timestamp());
 begin perform public.losi_chat_send_reply(b,t,false,r2,'Outra conversa',gm);raise exception 'Aceitou outra conversa';exception when others then if sqlerrm<>'RESPOSTA_INVALIDA' then raise;end if;end;
 perform public.losi_chat_send_reply(b,g,true,gr,'Resposta em grupo',gm);
 if public.losi_chat_reply_previews(a,array[gr])->gr::text->>'text'<>'Mensagem do grupo' then raise exception 'Citação do grupo ausente';end if;
 insert into public.losi_chat_uploads(id,user_id,group_id,kind,file_name,mime,byte_size,path,verified) values(up,b,g,'image','reply.png','image/png',100,b||'/'||up,true);
 select balance into start_balance from public.losi_chat_accounts where user_id=b;
 result:=public.losi_chat_send_reply(b,g,true,mr,'Legenda',gm,up);
 perform public.losi_chat_send_reply(b,g,true,mr,'Legenda',gm,up);
 if (select balance from public.losi_chat_accounts where user_id=b)<>start_balance-3 then raise exception 'Preço ou nova tentativa do anexo incorreto';end if;
 begin perform public.losi_chat_send_reply(b,g,true,mr,'Legenda',m,up);raise exception 'Alterou citação de envio concluído';exception when others then if sqlerrm<>'RESPOSTA_INVALIDA' then raise;end if;end;
 if has_function_privilege('authenticated','public.losi_chat_send_reply(uuid,uuid,boolean,uuid,text,uuid,uuid)','execute') or has_function_privilege('anon','public.losi_chat_reply_previews(uuid,uuid[])','execute') then raise exception 'RPC exposta';end if;
 update public.losi_chat_group_members set joined_at=clock_timestamp() where group_id=g and user_id=a;
 if public.losi_chat_reply_previews(a,array[gr])<>'{}'::jsonb then raise exception 'Histórico anterior à entrada vazou';end if;
end $$;
rollback;
