begin;
do $$ declare a uuid;b uuid;t uuid;g uuid:=gen_random_uuid();m uuid:=gen_random_uuid();gm uuid:=gen_random_uuid();status jsonb;delivery timestamptz;begin
 select creator_id into a from public.losi_chat_groups limit 1;
 select user_id into b from public.losi_chat_accounts where user_id<>a limit 1;
 if a is null or b is null then raise exception 'Duas contas são necessárias';end if;
 select id into t from public.losi_chat_threads where (user_a=a and user_b=b) or (user_a=b and user_b=a);
 if t is null then t:=gen_random_uuid();insert into public.losi_chat_threads(id,user_a,user_b) values(t,least(a,b),greatest(a,b));end if;
 insert into public.losi_chat_messages(id,thread_id,sender_id,body,created_at) values(m,t,a,'Verificação temporária',clock_timestamp());
 if (select count(*) from public.losi_chat_receipts where message_id=m)<>1 then raise exception 'Destinatários incorretos';end if;
 status:=public.losi_chat_receipt_status(a,array[m]);if status->m::text->>'status'<>'sent' then raise exception 'Estado inicial incorreto';end if;
 perform public.losi_chat_acknowledge(a,array[m],true);
 if exists(select 1 from public.losi_chat_receipts where message_id=m and read_at is not null) then raise exception 'Remetente forjou leitura';end if;
 perform public.losi_chat_acknowledge(b,array[m],false);
 status:=public.losi_chat_receipt_status(a,array[m]);if status->m::text->>'status'<>'delivered' then raise exception 'Entrega não registrada';end if;
 select delivered_at into delivery from public.losi_chat_receipts where message_id=m;
 perform public.losi_chat_acknowledge(b,array[m],true);
 perform public.losi_chat_acknowledge(b,array[m],true);
 status:=public.losi_chat_receipt_status(a,array[m]);if status->m::text->>'status'<>'read' then raise exception 'Leitura não registrada';end if;
 if delivery<>(select delivered_at from public.losi_chat_receipts where message_id=m) then raise exception 'Entrega não idempotente';end if;
 if public.losi_chat_receipt_status(b,array[m])<>'{}'::jsonb then raise exception 'Destinatário consultou recibos de terceiros';end if;
 insert into public.losi_chat_groups(id,owner_id,creator_id,name) values(g,a,a,'Grupo temporário');
 insert into public.losi_chat_group_members(group_id,user_id) values(g,a),(g,b);
 insert into public.losi_chat_messages(id,group_id,sender_id,body,created_at) values(gm,g,a,'Grupo temporário',clock_timestamp());
 if (select count(*) from public.losi_chat_receipts where message_id=gm)<>1 then raise exception 'Recibo do grupo incorreto';end if;
 update public.losi_chat_group_members set active=false where group_id=g and user_id=b;
 perform public.losi_chat_acknowledge(b,array[gm],true);
 if exists(select 1 from public.losi_chat_receipts where message_id=gm and read_at is not null) then raise exception 'Removido confirmou leitura';end if;
 perform set_config('test.receipt_sender',a::text,true);perform set_config('test.receipt_id',m::text,true);
end $$;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',gen_random_uuid(),'role','authenticated')::text,true);
do $$ begin
 if exists(select 1 from public.losi_chat_receipts where message_id=current_setting('test.receipt_id')::uuid) then raise exception 'Recibos expostos a terceiros';end if;
 begin update public.losi_chat_receipts set read_at=clock_timestamp() where message_id=current_setting('test.receipt_id')::uuid;raise exception 'Usuário alterou recibos diretamente';exception when insufficient_privilege then null;end;
end $$;
select set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('test.receipt_sender'),'role','authenticated')::text,true);
do $$ begin if not exists(select 1 from public.losi_chat_receipts where message_id=current_setting('test.receipt_id')::uuid) then raise exception 'Remetente sem acesso aos recibos';end if;end $$;
reset role;
rollback;
