import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import {webcrypto} from 'node:crypto';
const source=fs.readFileSync('supabase/functions/team-public-calendar/manual-profile.ts','utf8');const exports={};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,crypto:webcrypto});
const {resolveManualProfile}=exports;
function db(){const tables={collaborator_profiles:[],team_collaborators:[]};let collide=false;return {tables,setCollision(){collide=true},from(table){let filters=[],payload,mode='get';const q={select(){return q},eq(k,v){filters.push(x=>x[k]===v);return q},is(k,v){filters.push(x=>x[k]===v);return q},insert(v){payload=v;mode='insert';return q},update(v){payload=v;mode='update';return q},maybeSingle(){return run()},single(){return run()},then(resolve,reject){return run().then(resolve,reject)}};async function run(){if(mode==='insert'){const row={id:'profile-'+tables[table].length,calendar_token:'canonical-token',...payload};tables[table].push(row);if(collide){collide=false;return {data:null,error:{code:'23505'}}}return {data:row,error:null}}const rows=tables[table].filter(x=>filters.every(f=>f(x)));if(mode==='update')rows.forEach(x=>Object.assign(x,payload));return {data:rows[0]||null,error:null}}return q}}}
const a=db();const c={id:'manual-1',profile_id:null,name:'Nome Teste',whatsapp:'(11) 99999-1111',city:'Cotia',state:'SP',calendar_token:'original-link'};a.tables.team_collaborators.push(c);
const first=await resolveManualProfile(a,c);assert.match(first.losi_id,/^LOSI-\d{6}$/);assert.equal(c.profile_id,first.id);assert.equal(c.calendar_token,'original-link');
assert.equal((await resolveManualProfile(a,c)).id,first.id);assert.equal(a.tables.collaborator_profiles.length,1);
const other={...c,id:'manual-2',profile_id:null,name:'Nome diferente no fornecedor',whatsapp:'5511999991111'};a.tables.team_collaborators.push(other);const reused=await resolveManualProfile(a,other);assert.equal(reused.id,first.id);assert.equal(reused.full_name,'Nome Teste');assert.equal(a.tables.collaborator_profiles.length,1);
const b=db();const race={...c,id:'race',profile_id:null};b.tables.team_collaborators.push(race);b.setCollision();const resolved=await resolveManualProfile(b,race);assert.equal(race.profile_id,resolved.id);assert.equal(b.tables.collaborator_profiles.length,1);
await assert.rejects(()=>resolveManualProfile(db(),{...c,profile_id:null,whatsapp:'123'}),/corrigir o WhatsApp/);
console.log('OK: colaborador manual ganha ID, mantém link, reutiliza perfil existente, preserva nome original e trata criação concorrente.');
