import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import assert from 'node:assert/strict';
const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/team-event-summary.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports});
const events=[{id:'termas',title:'Termas da Mata',event_date:'2026-10-10',status:'open'},{id:'festa',title:'Festa',event_date:'2026-10-11',status:'draft'},{id:'cancelado',title:'Cancelado',event_date:'2026-10-09',status:'cancelled'},{id:'fim',title:'Encerrado',event_date:'2026-10-01',status:'completed'}];
const openings=[{id:'o1',event_id:'termas',title:'Recreador',slots:8},{id:'o2',event_id:'festa',title:'Guia',slots:2},{id:'o3',event_id:'cancelado',title:'Monitor',slots:9},{id:'o4',event_id:'fim',title:'Animador',slots:9}];
const applications=[...Array.from({length:4},(_,i)=>({id:'p'+i,event_id:'termas',opening_id:'o1',candidate_name:'Pessoa '+i,status:'confirmed',assigned_role:'Monitoria',attendance_status:i===0?'unavailable':i===1?'confirmed':null})),{id:'pending',event_id:'festa',opening_id:'o2',candidate_name:'Candidata',status:'pending',attendance_status:null,assigned_role:null},{id:'approved',event_id:'festa',opening_id:'o2',candidate_name:'Aprovada',status:'approved',attendance_status:null},{id:'removed',event_id:'termas',opening_id:'o1',candidate_name:'Retirada',status:'removed',attendance_status:'unavailable'},{id:'other',event_id:'cancelado',opening_id:'o3',candidate_name:'Cancelada',status:'pending'},{id:'ended',event_id:'fim',opening_id:'o4',candidate_name:'Encerrada',status:'confirmed'}];
let summary=exports.eventSummary(events,openings,applications);assert.equal(summary.counts.events,2);assert.equal(summary.counts.vacancies,6);assert.equal(summary.counts.pending,1);assert.equal(summary.counts.waiting,2);assert.equal(summary.counts.unavailable,1);assert.equal(summary.rows.vacancies[0].quantity,4);assert.equal(summary.rows.vacancies[0].eventTitle,'Termas da Mata');assert.equal(summary.rows.pending[0].name,'Candidata');assert.equal(summary.rows.pending[0].area,'candidates');assert.equal(summary.rows.waiting[0].detail,'Monitoria');assert.equal(summary.rows.unavailable[0].area,'scale');assert.equal(summary.rows.unavailable[0].name,'Pessoa 0');
for(const category of Object.keys(summary.rows))assert.ok(summary.rows[category].every(r=>!['cancelado','fim'].includes(r.eventId)));
// Overstaffing one vacancy must not consume vacancies in an unrelated event.
summary=exports.eventSummary(events,[{...openings[0],slots:1},openings[1]],applications);assert.equal(summary.counts.vacancies,2);assert.equal(summary.rows.vacancies.length,1);assert.equal(summary.rows.vacancies[0].eventId,'festa');
summary=exports.eventSummary([],openings,applications);assert.ok(Object.values(summary.counts).every(n=>n===0));
console.log('Resumo OK: cada total corresponde à lista, função personalizada ocupa vaga, eventos encerrados/cancelados excluídos, nomes e eventos corretos, excesso não mascara vagas de outro evento.');
