import { useEffect, useRef, useState } from 'react';
import { uploadChatFile } from '../lib/chat-upload';
import { chatAction, type ChatMessage } from '../lib/losi-chat';
import { LosiChatAudioRecorder } from './LosiChatAudioRecorder';
import '../losi-chat-attachments.css';

const formats: Record<string, string> = { m4a: 'audio/mp4', weba: 'audio/webm', mp4: 'video/mp4', mov: 'video/quicktime', webm: 'video/webm', jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', webp: 'image/webp', gif: 'image/gif', pdf: 'application/pdf', txt: 'text/plain', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' };
export const mediaCost = (file: File, text: string) => file.type.startsWith('audio/') ? 1 : file.type.startsWith('video/') ? 10 : file.type.startsWith('image/') ? text.trim() ? 3 : 2 : file.size <= 2097152 ? 2 : file.size <= 5242880 ? 3 : file.size <= 10485760 ? 4 : 8;
const sizeLabel = (size: number) => size < 1048576 ? `${Math.ceil(size / 1024)} KB` : `${(size / 1048576).toLocaleString('pt-BR', { maximumFractionDigits: 1 })} MB`;
function Paperclip() { return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="m9 15 7-7a3 3 0 0 0-4-4L4 12a5 5 0 0 0 7 7l9-9" /></svg>; }
function Microphone() { return <svg className="lc-audio-mic-icon" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="8" y="2.5" width="8" height="13" rx="4" /><path d="M5 11.5a7 7 0 0 0 14 0M12 18.5v3M9 21.5h6" /></svg>; }
function IconFallback() { return <span className="lc-audio-avatar-fallback" aria-hidden="true">LO</span>; }
const waveformBars = [9, 15, 22, 12, 27, 18, 11, 24, 30, 19, 13, 25, 34, 17, 11, 28, 20, 12, 26, 35, 19, 13, 29, 22, 16, 31, 24, 14, 27, 36, 21, 12, 24, 17, 28, 20, 11, 25, 32, 16, 10, 22, 29, 18, 13, 26, 20, 12, 24, 16, 28, 21, 14, 25, 31, 17, 11, 23, 29, 15, 10, 20, 26, 14];
function AudioWaveform({ progress, onSeek }: { progress: number; onSeek: (percent: number) => void }) { return <button type="button" className="lc-audio-waveform" aria-label="Avançar ou retroceder áudio" onClick={e => { const rect = e.currentTarget.getBoundingClientRect(); onSeek(Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width))); }}>{waveformBars.map((height, index) => <i key={index} style={{ height: `${height}px`, opacity: index / waveformBars.length <= progress ? .95 : .42 }} />)}</button>; }
const audioTime = (seconds: number) => !Number.isFinite(seconds) || seconds < 0 ? '0:00' : `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, '0')}`;

export function LosiChatComposer({ threadId, group, balance, hasNumber, onSent, onError, onText, text, setText, textSending }: { threadId: string; group: boolean; balance: number; hasNumber: boolean; onSent: (m: ChatMessage) => void; onError: (message: string) => void; onText: () => Promise<void>; text: string; setText: (s: string) => void; textSending: boolean }) {
  const [file, setFile] = useState<File | null>(null), [preview, setPreview] = useState(''), [busy, setBusy] = useState(false), [stage, setStage] = useState(''), [recording, setRecording] = useState(false);
  const picker = useRef<HTMLInputElement>(null), attachButton = useRef<HTMLButtonElement>(null), attempt = useRef<{ uploadId: string; requestId: string; uploaded: boolean; text: string } | null>(null), live = useRef(true), lock = useRef(false);
  useEffect(() => { live.current = true; return () => { live.current = false; }; }, []);
  useEffect(() => { if (!file || (!file.type.startsWith('image/') && !file.type.startsWith('video/') && !file.type.startsWith('audio/'))) { setPreview(''); return; } const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url); }, [file]);
  const cost = file ? mediaCost(file, text) : 1;
  function choose(f: File | undefined) { if (!f) return; const ext = f.name.split('.').at(-1)?.toLowerCase() ?? '', mime = formats[ext]; if (!mime || f.size < 1 || f.size > 20971520) { onError('Selecione JPG, PNG, WEBP, GIF, PDF, TXT, DOCX, XLSX, PPTX, MP4, MOV, WEBM, M4A ou WEBA de até 20 MB.'); return; } setFile(new File([f], f.name, { type: mime })); attempt.current = null; }
  async function send() { if (lock.current || textSending || recording) return; if (!file) { await onText(); return; } lock.current = true; setBusy(true); onError(''); if (!attempt.current) attempt.current = { uploadId: crypto.randomUUID(), requestId: crypto.randomUUID(), uploaded: false, text: text.trim() }; const a = attempt.current; try { if (!a.uploaded) { setStage('Preparando arquivo…'); const p = await chatAction<{ signedUrl: string; mime: string }>('prepare-media', { threadId, group, uploadId: a.uploadId, fileName: file.name, size: file.size }); setStage('Enviando arquivo… 0%'); await uploadChatFile(p.signedUrl, file, p.mime, percent => { if (live.current) setStage(`Enviando arquivo… ${percent}%`); }); a.uploaded = true; } setStage('Conferindo e enviando…'); const d = await chatAction<{ message: ChatMessage }>('send-media', { uploadId: a.uploadId, requestId: a.requestId, text: a.text }); if (live.current) { setFile(null); setText(''); attempt.current = null; } onSent(d.message); } catch (e) { if (live.current) onError(e instanceof Error ? e.message : 'Não foi possível enviar. Nenhum crédito foi descontado nesta tentativa.'); } finally { lock.current = false; if (live.current) { setBusy(false); setStage(''); } } }
  const fixedCaption = attempt.current?.text;
  return <div className="lc-compose-wrap">{file && <section className={`lc-attachment-preview${file.type.startsWith('video/') ? ' lc-video-preview' : file.type.startsWith('audio/') ? ' lc-audio-preview' : ''}`} aria-label="Prévia do anexo">{preview ? (file.type.startsWith('audio/') ? <audio src={preview} controls preload="metadata" aria-label="Ouvir gravação antes de enviar" /> : file.type.startsWith('video/') ? <video src={preview} controls playsInline preload="metadata" aria-label="Prévia do vídeo selecionado" /> : <img src={preview} alt="Prévia da imagem selecionada" />) : <Paperclip />}<div><strong>{file.type.startsWith('audio/') ? 'Mensagem de áudio' : file.name}</strong><small>{sizeLabel(file.size)} · {cost} {cost === 1 ? 'crédito' : 'créditos'}{file.type.startsWith('image/') && text.trim() ? ' com texto' : ''}</small>{fixedCaption !== undefined && fixedCaption !== text.trim() && <small>A nova tentativa mantém a legenda original. Remova o arquivo para alterar.</small>}</div><button type="button" disabled={busy} onClick={() => { setFile(null); attempt.current = null; attachButton.current?.focus(); }} aria-label="Remover anexo">×</button></section>}<form className="lc-composer" onSubmit={e => { e.preventDefault(); void send(); }}><input ref={picker} className="lc-file-picker" type="file" accept={Object.keys(formats).filter(ext => !formats[ext].startsWith('audio/')).map(x => '.' + x).join(',')} onChange={e => { choose(e.target.files?.[0]); e.target.value = ''; }} disabled={busy || textSending || recording} tabIndex={-1} aria-label="Selecionar imagem, vídeo ou documento" /><button ref={attachButton} type="button" aria-label="Adicionar imagem, vídeo ou documento" disabled={busy || textSending || recording} onClick={() => picker.current?.click()}><Paperclip /></button><input aria-label={file ? 'Legenda do anexo' : 'Mensagem'} disabled={busy || textSending || recording || Boolean(attempt.current)} placeholder={file ? 'Legenda (opcional)' : 'Digite uma mensagem'} value={text} onChange={e => setText(e.target.value)} maxLength={4000} /><LosiChatAudioRecorder disabled={busy || textSending || Boolean(file) || !hasNumber || balance < 1} onFile={choose} onError={onError} onRecording={setRecording} /><button className="lc-send" type="submit" aria-label={`Enviar por ${cost} ${cost === 1 ? 'crédito' : 'créditos'}`} title={`Enviar · ${cost} ${cost === 1 ? 'crédito' : 'créditos'}`} disabled={busy || textSending || recording || (!file && !text.trim()) || !hasNumber || balance < cost}><svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="m3 3 18 9-18 9 4-9Z M7 12h14" /></svg></button></form>{busy && <p className="lc-upload-status" role="status">{stage}</p>}{file && balance < cost && <p className="lc-upload-status" role="status">Saldo insuficiente: este envio custa {cost} {cost === 1 ? 'crédito' : 'créditos'}.</p>}</div>;
}

export function LosiChatAttachment({ message, own, onDeleted, profilePhoto = message.sender_photo, profileInitials }: { message: ChatMessage; own: boolean; onDeleted: (id: string) => void; profilePhoto?: string | null; profileInitials?: string }) {
  const [url, setUrl] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [reload, setReload] = useState(0), [visible, setVisible] = useState(false), [playing, setPlaying] = useState(false), [duration, setDuration] = useState(0), [currentTime, setCurrentTime] = useState(0), [menu, setMenu] = useState(false), [confirm, setConfirm] = useState(false);
  const container = useRef<HTMLDivElement>(null), timer = useRef<ReturnType<typeof setTimeout> | null>(null), start = useRef({ x: 0, y: 0 }), menuRef = useRef<HTMLDivElement>(null), audioPlayer = useRef<HTMLAudioElement>(null), player = useRef<HTMLVideoElement>(null), previousConfirm = useRef(false);
  const attachment = message.attachment;
  const cancelPress = () => { if (timer.current) clearTimeout(timer.current); timer.current = null; };
  const closeMenu = () => { setMenu(false); setConfirm(false); container.current?.focus(); };
  useEffect(() => () => cancelPress(), []);
  useEffect(() => { if (!menu) return; menuRef.current?.querySelector<HTMLButtonElement>(previousConfirm.current && !confirm ? '[data-delete-everyone]' : 'button')?.focus(); previousConfirm.current = confirm; const close = (e: PointerEvent) => { if (!container.current?.contains(e.target as Node)) closeMenu(); }; document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close); }, [menu, confirm]);
  useEffect(() => { if (!container.current) return; if (typeof IntersectionObserver === 'undefined') { setVisible(true); return; } const observer = new IntersectionObserver(entries => { if (entries.some(e => e.isIntersecting)) { setVisible(true); observer.disconnect(); } }, { rootMargin: '200px' }); observer.observe(container.current); return () => observer.disconnect(); }, []);
  useEffect(() => { if (!attachment || attachment.kind === 'document' || !visible) return; let live = true; void chatAction<{ url: string }>('media-url', { messageId: message.id }).then(d => { if (live) { setUrl(d.url); setError(''); } }).catch(() => { if (live) setError('Não foi possível carregar a mídia.'); }); return () => { live = false; }; }, [message.id, attachment?.kind, reload, visible]);
  if (!attachment) return null;
  async function download() { if (busy) return; setBusy(true); setError(''); try { const d = await chatAction<{ url: string }>('media-url', { messageId: message.id, download: true }); window.location.assign(d.url); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível baixar.'); } finally { setBusy(false); } }
  async function remove(everyone: boolean) { if (busy) return; setBusy(true); setError(''); try { await chatAction('delete-media', { messageId: message.id, everyone }); onDeleted(message.id); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível excluir.'); } finally { setBusy(false); setMenu(false); setConfirm(false); } }
  async function toggleAudio() { if (!audioPlayer.current || busy) return; if (audioPlayer.current.paused) await audioPlayer.current.play(); else audioPlayer.current.pause(); }
  const audioBubble = attachment.kind === 'audio' && <div className={`lc-audio-message${own ? ' is-own' : ''}`} aria-label="Mensagem de áudio"><span className="lc-audio-avatar">{profilePhoto ? <img src={profilePhoto} alt="" /> : profileInitials || <IconFallback />}<span className="lc-audio-mic-badge"><Microphone /></span></span><button type="button" className="lc-audio-play" disabled={busy || !url} onClick={() => void toggleAudio()} aria-label={playing ? 'Pausar áudio' : 'Reproduzir áudio'}>{playing ? <span className="lc-audio-pause" aria-hidden="true" /> : <span className="lc-audio-play-triangle" aria-hidden="true" />}</button><div className="lc-audio-track"><AudioWaveform progress={duration ? currentTime / duration : 0} onSeek={ratio => { if (audioPlayer.current && duration) { audioPlayer.current.currentTime = duration * ratio; setCurrentTime(duration * ratio); } }} /><div className="lc-audio-meta"><span>{busy ? 'Abrindo áudio…' : audioTime(currentTime || duration)}</span><Microphone /></div></div><audio ref={audioPlayer} src={url || undefined} preload="metadata" aria-label="Mensagem de áudio" onLoadedMetadata={e => setDuration(e.currentTarget.duration)} onTimeUpdate={e => setCurrentTime(e.currentTarget.currentTime)} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onEnded={() => { setPlaying(false); setCurrentTime(0); }} onError={() => { setUrl(''); setError('Não foi possível reproduzir. Reabra o áudio ou baixe o arquivo.'); }} /><span className="lc-audio-status" aria-live="polite">{url ? '' : busy ? 'Abrindo áudio…' : 'Toque para carregar o áudio'}</span></div>;
  return <div ref={container} className="lc-sent-attachment" tabIndex={0} aria-label="Arquivo enviado. Segure para abrir as opções." onPointerDown={e => { if (e.button !== 0 || menu) return; cancelPress(); start.current = { x: e.clientX, y: e.clientY }; timer.current = setTimeout(() => { setMenu(true); timer.current = null; }, 500); }} onPointerMove={e => { if (Math.hypot(e.clientX - start.current.x, e.clientY - start.current.y) > 12) cancelPress(); }} onPointerUp={cancelPress} onPointerCancel={cancelPress} onContextMenu={e => { e.preventDefault(); cancelPress(); setMenu(true); }} onKeyDown={e => { if (e.key === 'Escape') closeMenu(); else if (e.key === 'ContextMenu' || (e.key === 'F10' && e.shiftKey)) { e.preventDefault(); setMenu(true); } }}>{audioBubble}{attachment.kind === 'video' && (url ? <video ref={player} src={url} controls playsInline preload="metadata" aria-label={`Vídeo: ${attachment.file_name}`} onError={() => { setUrl(''); setError('Não foi possível reproduzir o vídeo.'); }} /> : <button type="button" disabled={busy} onClick={() => void (async () => { setBusy(true); try { const d = await chatAction<{ url: string }>('media-url', { messageId: message.id }); setUrl(d.url); } finally { setBusy(false); } })()}>{busy ? 'Abrindo vídeo…' : 'Ver vídeo'}</button>)}{attachment.kind === 'image' && url && <img loading="lazy" src={url} alt={attachment.file_name} onError={() => { setUrl(''); setError('A imagem não carregou.'); }} />}{attachment.kind === 'document' && <button type="button" onClick={() => setMenu(true)}><Paperclip /><strong>{attachment.file_name}</strong></button>}{menu && <div ref={menuRef} className="lc-media-menu" aria-label="Opções do arquivo">{confirm ? <><p>Excluir este arquivo para todos? Os créditos do envio não são devolvidos.</p><button type="button" disabled={busy} onClick={() => void remove(true)}>Confirmar exclusão</button><button type="button" disabled={busy} onClick={() => setConfirm(false)}>Voltar</button></> : <><button type="button" disabled={busy} onClick={() => { closeMenu(); void download(); }}>Baixar arquivo</button><button type="button" disabled={busy} onClick={() => void remove(false)}>Excluir só para mim</button>{own && <button type="button" data-delete-everyone disabled={busy} onClick={() => setConfirm(true)}>Excluir para todos</button>}<button type="button" onClick={closeMenu}>Fechar</button></>}</div>}{error && <p role="status">{error}{attachment.kind === 'image' && <button type="button" onClick={() => setReload(n => n + 1)}>Recarregar</button>}</p>}</div>;
}
