import { useEffect, useRef, useState } from 'react';
import { chatAction, formatLosiNumber } from '../lib/losi-chat';
import '../losi-chat-groups.css';
type Member={name:string;photo:string|null;number:string;owner:boolean;self:boolean};
type Group={id:string;name:string;description:string;isOwner:boolean;members:Member[]};
export function LosiChatGroupCreate({onCreated,onCancel,hasNumber}:{onCreated:(id:string)=>Promise<void>;onCancel:()=>void;hasNumber:boolean}){
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[number,setNumber]=useState(''),[numbers,setNumbers]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef<{id:string;key:string}|null>(null);
 function addNumber(){const n=number.replace(/\D/g,'');if(!/^[1-9][0-9]{8}$/.test(n)){setError('Informe um número LOSI com 9 dígitos.');return;}if(numbers.length>=99){setError('O grupo pode ter até 100 participantes, incluindo você.');return;}setNumbers(old=>old.includes(n)?old:[...old,n]);setNumber('');setError('');}
 async function create(){if(busy)return;if(number.trim()){setError('Adicione o número digitado à lista antes de criar o grupo.');return;}setBusy(true);setError('');const key=JSON.stringify([name.trim(),description,[...numbers].sort()]);if(!request.current||request.current.key!==key)request.current={id:crypto.randomUUID(),key};try{const d=await chatAction<{groupId:string}>('group-create',{requestId:request.current.id,name,description,numbers});await onCreated(d.groupId);}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar o grupo.');}finally{setBusy(false);}}
 return <div className="lc-group-panel"><div className="lc-group-panel-heading"><h2>Novo grupo</h2><button type="button" disabled={busy} onClick={onCancel}>Voltar</button></div><p>Troque experiências com até 100 participantes. Cada texto enviado custa 1 crédito; receber é gratuito.</p>{!hasNumber&&<p className="lc-group-error"><a href="/meus-servicos">Compre ou resgate seu número LOSI para criar um grupo.</a></p>}<form onSubmit={e=>{e.preventDefault();void create();}}><label>Nome do grupo<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} disabled={busy} placeholder="Ex.: Parceiros de eventos"/></label><label>Descrição <small>opcional</small><textarea rows={3} maxLength={500} value={description} onChange={e=>setDescription(e.target.value)} disabled={busy}/></label><label>Participantes pelo número LOSI<input inputMode="numeric" value={number} maxLength={11} onChange={e=>setNumber(e.target.value)} disabled={busy} placeholder="154.444.566"/></label><button type="button" className="lc-group-secondary" onClick={addNumber} disabled={busy||!hasNumber}>Adicionar à lista</button><ul className="lc-group-number-list">{numbers.map(n=><li key={n}><span>{formatLosiNumber(n)}</span><button type="button" aria-label={`Remover ${formatLosiNumber(n)} da lista`} disabled={busy} onClick={()=>setNumbers(old=>old.filter(x=>x!==n))}>Remover</button></li>)}</ul><button className="lc-group-primary" disabled={busy||!hasNumber||!name.trim()}>{busy?'Criando…':'Criar grupo'}</button></form>{error&&<p className="lc-group-error" role="alert">{error}</p>}</div>;
}
export function LosiChatGroupDetails({groupId,onClose,onChanged,onLeft}:{groupId:string;onClose:()=>void;onChanged:()=>Promise<void>;onLeft:()=>void}){
 const [group,setGroup]=useState<Group|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[number,setNumber]=useState(''),[confirm,setConfirm]=useState<{operation:string;number?:string;label:string}|null>(null);
 const confirmationRef=useRef<HTMLDivElement>(null);
 const confirmationOrigin=useRef<HTMLElement|null>(null);
 function ask(c:{operation:string;number?:string;label:string}){confirmationOrigin.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setConfirm(c);}
 useEffect(()=>{if(confirm){confirmationRef.current?.focus({preventScroll:true});confirmationRef.current?.scrollIntoView({block:'nearest'});}else confirmationOrigin.current?.focus({preventScroll:true});},[confirm]);
 useEffect(()=>{let live=true;chatAction<{group:Group}>('group-details',{groupId}).then(d=>{if(live){setGroup(d.group);setName(d.group.name);setDescription(d.group.description);}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'Não foi possível abrir o grupo.');});return()=>{live=false;};},[groupId]);
 async function act(operation:string,n?:string){if(busy)return;setBusy(true);setError('');setNotice('');try{await chatAction('group-manage',{groupId,operation,number:n,name,description});setConfirm(null);if(operation==='leave'){onLeft();return;}const d=await chatAction<{group:Group}>('group-details',{groupId});setGroup(d.group);setName(d.group.name);setDescription(d.group.description);setNumber('');setNotice('Grupo atualizado.');await onChanged();}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar o grupo.');}finally{setBusy(false);}}
 return <section className="lc-group-details" aria-label="Dados do grupo"><div className="lc-group-panel"><div className="lc-group-panel-heading"><h2>Dados do grupo</h2><button type="button" disabled={busy} onClick={onClose}>Voltar à conversa</button></div>{!group&&!error&&<p role="status">Carregando participantes…</p>}{group&&<><h3>{group.name}</h3><p>{group.description||'Sem descrição.'}</p><p>{group.members.length} participantes · {group.isOwner?'Você administra este grupo.':'Você participa deste grupo.'}</p>{group.isOwner&&<><form onSubmit={e=>{e.preventDefault();void act('rename');}}><label>Nome<input required value={name} maxLength={80} onChange={e=>setName(e.target.value)} disabled={busy}/></label><label>Descrição<textarea value={description} maxLength={500} rows={3} onChange={e=>setDescription(e.target.value)} disabled={busy}/></label><button className="lc-group-primary" disabled={busy||!name.trim()}>Salvar dados</button></form><form onSubmit={e=>{e.preventDefault();void act('add',number.replace(/\D/g,''));}}><label>Adicionar participante pelo número LOSI<input required inputMode="numeric" maxLength={11} value={number} onChange={e=>setNumber(e.target.value)} disabled={busy} placeholder="154.444.566"/></label><button className="lc-group-secondary" disabled={busy||!number.trim()}>Adicionar participante</button></form></>}<ul className="lc-group-members">{group.members.map(m=><li key={m.number}><span className="lc-group-member-avatar">{m.photo?<img src={m.photo} alt=""/>:m.name.slice(0,2).toUpperCase()}</span><div><strong>{m.name}{m.self?' (você)':''}</strong><small>{formatLosiNumber(m.number)}{m.owner?' · Administrador':''}</small>{group.isOwner&&!m.self&&<div className="lc-group-member-actions"><button disabled={busy} type="button" onClick={()=>ask({operation:'remove',number:m.number,label:`Remover ${m.name} do grupo?`})}>Remover</button><button disabled={busy} type="button" onClick={()=>ask({operation:'transfer',number:m.number,label:`Transferir a administração para ${m.name}?`})}>Tornar administrador</button></div>}</div></li>)}</ul>{!group.isOwner&&<button type="button" className="lc-group-secondary" disabled={busy} onClick={()=>ask({operation:'leave',label:'Sair deste grupo? Você deixará de receber e acessar as mensagens dele.'})}>Sair do grupo</button>}{group.isOwner&&<p>Para sair, transfira a administração para outro participante.</p>}{confirm&&<div ref={confirmationRef} tabIndex={-1} className="lc-group-confirm" role="group" aria-label="Confirmar alteração no grupo"><p>{confirm.label}</p><div><button type="button" disabled={busy} className="lc-group-primary" onClick={()=>void act(confirm.operation,confirm.number)}>{busy?'Aguarde…':'Confirmar'}</button><button type="button" disabled={busy} className="lc-group-secondary" onClick={()=>setConfirm(null)}>Voltar</button></div></div>}</>}{error&&<p className="lc-group-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</div></section>;
}
