import { useState } from "react";
import { calculateOperations, isOperations, type Operations } from "../../supabase/functions/losi-ai-content/planning-operations";
import type { SupplierResult } from "../../supabase/functions/losi-ai-content/planning-suppliers";
import "../planning-operations.css";
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export function PlanningOperations({operations,suppliers,onChange}:{operations?:Operations;suppliers?:SupplierResult;onChange?:(value:Operations)=>void}){
 const [error,setError]=useState("");
 const commit=(next:Operations)=>{if(!isOperations(next)){setError("Use números positivos dentro dos limites indicados.");return;}try{calculateOperations(next);}catch{setError("O valor ultrapassou o limite de cálculo. Reduza quantidade ou custo unitário.");return;}setError("");onChange?.(next);};
 const result=operations?calculateOperations(operations):null;
 const editable=!!onChange;
 const value=(v:string)=>v===""?null:Number(v);
 function activity(index:number,key:string,v:string){if(!operations||!onChange)return;commit({...operations,activities:operations.activities.map((a,i)=>i===index?{...a,[key]:key==="method"?v:value(v),basis:"assumption",sourceUrls:[],explanation:"Parâmetros ajustados pelo responsável; confirme capacidade, público e execução."}:a)});}
 function cost(index:number,key:string,v:string){if(!operations||!onChange)return;commit({...operations,costs:operations.costs.map((c,i)=>i===index?{...c,[key]:key==="label"||key==="unit"?v:key==="activityIndex"?value(v):key==="unitCost"?value(v):Number(v||0),basis:key==="unitCost"&&v===""?"quote_required":"informed",sourceUrls:[],explanation:"Valor ou quantidade ajustado pelo responsável."}:c)});}
 return <section className="plan-operations" aria-label="Equipe, custos e fornecedores">{error&&<p role="alert">{error}</p>}
  {result&&operations&&<details className="plan-calculations" ><summary>Equipe e custos · {result.people===null?"equipe a definir":result.people+" profissionais"} · {result.incomplete?"custo parcial ":"custo "}{money(result.totalCost)}</summary>
   <p><strong>Cenário:</strong> {operations.scenario}</p><p>As fórmulas são verificadas automaticamente. Premissas pesquisadas, informadas e hipóteses ficam identificadas. Equipes de atividades são somadas sem reaproveitamento; revise horários e simultaneidade.</p>
   <h3>Dimensionamento por atividade</h3>
   {!result.activities.length&&<p>Informe à Lia as atividades, a demanda e a duração para dimensionar a equipe.</p>}
   {result.activities.map((a,i)=><div className="plan-operation-row" key={i}><h4>{a.activity} · {a.role}</h4><p><strong>{a.people===null?"Quantidade pendente":a.people+" profissional(is)"}</strong> · {a.basis==="researched"?"Premissa pesquisada":a.basis==="informed"?"Premissa do briefing":"Hipótese a confirmar"}</p><p>{a.explanation}</p><div className="plan-operation-inputs"><label>Regra · {a.activity}<select disabled={!editable} value={a.method} onChange={e=>activity(i,"method",e.target.value)}><option value="ratio">Demanda / capacidade</option><option value="throughput">Atendimentos por hora</option><option value="fixed">Equipe fixa</option></select></label>{a.method==="fixed"?<label>Equipe fixa · {a.activity}<input type="number" min="0" max="10000" step="1" disabled={!editable} value={a.fixedPeople??""} onChange={e=>activity(i,"fixedPeople",e.target.value)}/></label>:<><label>Demanda · {a.activity}<input type="number" min="0" max="1000000" disabled={!editable} value={a.demand??""} onChange={e=>activity(i,"demand",e.target.value)}/></label><label>Capacidade por profissional{a.method==="throughput"?" / hora":""} · {a.activity}<input type="number" min="0" max="1000000" disabled={!editable} value={a.capacity??""} onChange={e=>activity(i,"capacity",e.target.value)}/></label>{a.method==="throughput"&&<label>Horas · {a.activity}<input type="number" min="0" max="1000000" step="0.5" disabled={!editable} value={a.hours??""} onChange={e=>activity(i,"hours",e.target.value)}/></label>}</>}</div>{a.sourceUrls.map(url=><a key={url} href={url} target="_blank" rel="noopener noreferrer">Fonte da premissa</a>)}</div>)}
   <h3>Composição de custos</h3><p>Use custos de contratação, material, locação e transporte. O preço de venda pesquisado de um serviço não é automaticamente o seu custo.</p>
   {result.costs.map((c,i)=><div className="plan-operation-row" key={i}><h4>{c.label} · {c.total===null?"Cotação pendente":money(c.total)}</h4><p>{c.basis==="researched"?"Custo pesquisado":c.basis==="estimate"?"Estimativa":c.basis==="informed"?"Custo informado":"Valor a cotar"} · {c.explanation}</p><div className="plan-operation-inputs">{editable&&<label>Descrição do custo · {c.label}<input maxLength={160} value={c.label} onChange={e=>cost(i,"label",e.target.value)}/></label>}<label>Quantidade · {c.label}<input type="number" min="0" max="1000000" step="0.01" disabled={!editable||c.activityIndex!==null} value={c.quantity??""} onChange={e=>cost(i,"quantity",e.target.value)}/></label><label>Custo unitário (R$) · {c.label}<input type="number" min="0" max="1000000" step="0.01" disabled={!editable} value={c.unitCost??""} placeholder="A cotar" onChange={e=>cost(i,"unitCost",e.target.value)}/></label>{c.activityIndex!==null&&<label>Unidades por profissional · {c.label}<input type="number" min="0" max="1000" step="0.01" disabled={!editable} value={c.unitsPerPerson} onChange={e=>cost(i,"unitsPerPerson",e.target.value)}/></label>}</div><small>Unidade: {c.unit}. {c.activityIndex!==null?"Quantidade acompanha o dimensionamento da equipe.":"Quantidade independente da equipe."}</small>{editable&&<button type="button" onClick={()=>commit({...operations,costs:operations.costs.filter((_,index)=>index!==i)})}>Remover custo · {c.label}</button>}{c.sourceUrls.map(url=><a key={url} href={url} target="_blank" rel="noopener noreferrer">Fonte do custo</a>)}</div>)}
   {editable&&<button type="button" onClick={()=>commit({...operations,costs:[...operations.costs,{label:"Custo adicional "+(operations.costs.length+1),unit:"unidade",quantity:1,unitCost:null,activityIndex:null,unitsPerPerson:1,basis:"quote_required",explanation:"Preencha o custo unitário para incluir no total.",sourceUrls:[]}]})} disabled={operations.costs.length>=40}>Adicionar custo</button>}
   <div className="plan-operation-inputs">{(["contingencyPercent","taxPercent","marginPercent"] as const).map((key,i)=><label key={key}>{["Reserva de contingência (%)","Tributos estimados (%)","Margem sobre venda (%)"][i]}<input type="number" min="0" max="100" step="0.1" disabled={!editable} value={operations[key]} onChange={e=>commit({...operations,[key]:Number(e.target.value||0)})}/></label>)}</div>
   <dl className="plan-cost-totals"><div><dt>{result.incomplete?"Subtotal parcial":"Subtotal"}</dt><dd>{money(result.subtotal)}</dd></div><div><dt>Reserva</dt><dd>{money(result.reserve)}</dd></div><div><dt>{result.incomplete?"Custo parcial":"Custo total"}</dt><dd>{money(result.totalCost)}</dd></div><div><dt>Preço sugerido</dt><dd>{result.suggestedPrice===null?"A definir":money(result.suggestedPrice)}</dd></div></dl>
   {result.incomplete&&<p role="status">Há parâmetros ou custos pendentes. O total é parcial e o preço final ainda não pode ser calculado.</p>}{result.invalidMargin&&<p role="alert">Tributos e margem juntos devem ficar abaixo de 100%.</p>}
   <p>Preço sugerido = custo com reserva / (1 − tributos − margem). Revise o período dos custos e os tributos aplicáveis ao seu negócio.</p>
  </details>}
  {suppliers&&<details className="plan-supplier-matches"><summary>Fornecedores LOSI · {suppliers.items.length?suppliers.items.length+" sugestões":suppliers.status==="unavailable"?"consulta indisponível":"sem correspondências"}</summary><p>{suppliers.message}</p>{suppliers.items.map(s=><div className="plan-operation-row" key={s.id}><h4>{s.name}</h4><p>{[s.cit…4414 tokens truncated…lan-operations{--op-text:#f5e2b7;--op-border:#40546e;--op-bg:#10253f;--op-muted:#c9d3e1}.wp-form .plan-operations p{color:#c9d3e1}@media(max-width:760px){.plan-operation-inputs{grid-template-columns:1fr}.plan-operation-inputs :is(input,select){font-size:16px}.plan-cost-totals div{flex-wrap:wrap}}
