import { type FormEvent, useEffect, useState } from "react";
import { teamRequest } from "../lib/team-management";
type Person={id:string;losi_id:string;full_name:string;professional_name:string|null;city:string|null;state:string|null;photo_url:string|null;created_at:string;whatsapp_masked:string};
export function TeamDirectory({businessId}:{businessId:string}) {
 const [query,setQuery]=useState(""),[applied,setApplied]=useState(""),[page,setPage]=useState(0),[retry,setRetry]=useState(0);
 const [people,setPeople]=useState<Person[]>([]),[total,setTotal]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{let cancelled=false;setBusy(true);setError("");setPeople([]);void teamRequest({action:"directory",businessId,query:applied,page}).then(data=>{if(!cancelled){setPeople(data.people);setTotal(data.total);}}).catch(err=>{if(!cancelled)setError(err.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[businessId,applied,page,retry]);
 async function copyId(id:string){try{await navigator.clipboard.writeText(id);setNotice("ID "+id+" copiado.");}catch{setNotice("Selecione e copie o ID exibido no cadastro: "+id);}}
 return <section className="team-section team-directory"><div className="team-section-head"><div><h2>Colaboradores cadastrados</h2><p className="team-section-help">Identidades de colaboradores que ainda não fazem parte da sua rede. Localize e copie o ID para ajudar a pessoa a recuperar o acesso.</p></div></div>
  <form className="team-search-row" onSubmit={event=>{event.preventDefault();setApplied(query.trim());setPage(0);setNotice("");setRetry(v=>v+1);}}><label>Buscar colaborador<input type="search" placeholder="ID, nome completo, nome de tio ou WhatsApp com DDD" value={query} onChange={e=>setQuery(e.target.value)} /></label><button className="team-primary" disabled={busy}>Buscar</button></form>
  <p className="team-section-help">Para buscar por WhatsApp, informe o número completo com DDD. Esta lista mostra o ID e a identificação; o calendário pessoal permanece privado.</p>
  {notice&&<p className="team-manager-notice" role="status">{notice}</p>}
  {error&&<div role="alert" className="team-manager-error"><p>{error}</p><button type="button" className="team-secondary" onClick={()=>setRetry(v=>v+1)}>Tentar novamente</button></div>}
  {busy?<p role="status">Carregando colaboradores...</p>:!error&&<><p className="team-result-count">{total} {total===1?"colaborador encontrado":"colaboradores encontrados"} · mais recentes primeiro</p><div className="team-directory-list">{people.length?people.map(person=><article key={person.id}>
   <div className="team-directory-person">{person.photo_url?<img src={person.photo_url} alt="" />:<span className="team-directory-initial">{(person.professional_name||person.full_name).slice(0,1).toUpperCase()}</span>}<div><strong>{person.professional_name||person.full_name}</strong>{person.professional_name&&<span>{person.full_name}</span>}<span>{[person.city,person.state].filter(Boolean).join(" / ")||"Cidade não informada"} · {person.whatsapp_masked}</span><small>Cadastrado em {new Date(person.created_at).toLocaleDateString("pt-BR")}</small></div></div><div className="team-directory-id"><strong>{person.losi_id}</strong><button type="button" className="team-secondary" onClick={()=>void copyId(person.losi_id)}>Copiar ID</button></div>
  </article>):<div className="team-empty">Nenhum colaborador encontrado fora da sua rede.</div>}</div><div className="team-directory-pagination"><button type="button" className="team-secondary" disabled={!page} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page+1} de {Math.max(1,Math.ceil(total/25))}</span><button type="button" className="team-secondary" disabled={(page+1)*25>=total} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></>}
 </section>;
}
type Provider={business_name:string;slug:string;city:string|null;state:string|null;whatsapp:string;logo_url:string|null};
export function TeamProviderImport({businessId,onAdded}:{businessId:string;onAdded:()=>Promise<void>}) {
 const [url,setUrl]=useState(""),[provider,setProvider]=useState<Provider|null>(null),[already,setAlready]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function find(event:FormEvent){event.preventDefault();setBusy(true);setError("");setNotice("");setProvider(null);try{const data=await teamRequest({action:"provider",businessId,url});setProvider(data.provider);setAlready(data.alreadyInNetwork);}catch(err){setError(err instanceof Error?err.message:"Não foi possível localizar o perfil.");}finally{setBusy(false);}}
 async function add(){setBusy(true);setError("");try{const data=await teamRequest({action:"addProvider",businessId,url});setAlready(true);setNotice(data.alreadyInNetwork?"Este fornecedor já está na sua rede.":"Fornecedor adicionado à sua rede.");await onAdded();}catch(err){setError(err instanceof Error?err.message:"Não foi possível adicionar.");}finally{setBusy(false);}}
 return <div className="team-provider-import"><h3>Adicionar pelo perfil público</h3><p>Já combinou de trabalhar com outro fornecedor? Cole o link, confira os dados e salve na sua rede.</p><form className="team-search-row" onSubmit={find}><label>Link do perfil público<input type="url" required disabled={busy} placeholder="https://losiconecta.com.br/fornecedor/..." value={url} onChange={e=>{setUrl(e.target.value);setProvider(null);setError("");setNotice("");}} /></label><button className="team-secondary" disabled={busy}>{busy?"Aguarde...":"Localizar perfil"}</button></form>
  {error&&<p className="team-manager-error" role="alert">{error}</p>}{notice&&<p className="team-manager-notice" role="status">{notice}</p>}
  {provider&&<div className="team-provider-result"><div><strong>{provider.business_name}</strong><span>{[provider.city,provider.state].filter(Boolean).join(" / ")} · WhatsApp {provider.whatsapp}</span><a href={"/fornecedor/"+provider.slug} target="_blank" rel="noopener noreferrer">Ver perfil público</a></div><button type="button" className="team-primary" disabled={busy||already} onClick={()=>void add()}>{already?"Já está na rede":"Adicionar à minha rede"}</button></div>}
 </div>;
}
