/* eslint-disable */
// @ts-nocheck

// This file is auto-generated by TanStack Router.
// It is committed so CI/Vercel can resolve the router entry deterministically.

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as EntrarImport } from './routes/entrar'
import { Route as IndexImport } from './routes/index'
import { Route as MeuPerfilImport } from './routes/meu-perfil'
import { Route as PainelImport } from './routes/painel'

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const EntrarRoute = EntrarImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MeuPerfilRoute = MeuPerfilImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => rootRoute,
} as any)

const PainelRoute = PainelImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRoute,
} as any)

const rootRouteChildren = {
  IndexRoute,
  AdminRoute,
  EntrarRoute,
  MeuPerfilRoute,
  PainelRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
