/* eslint-disable */

// @ts-nocheck

// This file is automatically generated by TanStack Router.
// It is committed here so CI/build environments can resolve the route tree.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MeuPerfilRouteImport } from './routes/meu-perfil'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as FornecedorSlugRouteImport } from './routes/fornecedor/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)

const MeuPerfilRoute = MeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => rootRouteImport,
} as any)

const FornecedorSlugRoute = FornecedorSlugRouteImport.update({
  id: '/fornecedor/$slug',
  path: '/fornecedor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/entrar': typeof EntrarRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/painel': typeof PainelRoute
  '/buscar': typeof BuscarRoute
  '/fornecedor/$slug': typeof FornecedorSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/entrar': typeof EntrarRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/painel': typeof PainelRoute
  '/buscar': typeof BuscarRoute
  '/fornecedor/$slug': typeof FornecedorSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/entrar': typeof EntrarRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/painel': typeof PainelRoute
  '/buscar': typeof BuscarRoute
  '/fornecedor/$slug': typeof FornecedorSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/entrar' | '/meu-perfil' | '/painel' | '/buscar' | '/fornecedor/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/entrar' | '/meu-perfil' | '/painel' | '/buscar' | '/fornecedor/$slug'
  id: '__root__' | '/' | '/admin' | '/entrar' | '/meu-perfil' | '/painel' | '/buscar' | '/fornecedor/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EntrarRoute: typeof EntrarRoute
  MeuPerfilRoute: typeof MeuPerfilRoute
  PainelRoute: typeof PainelRoute
  BuscarRoute: typeof BuscarRoute
  FornecedorSlugRoute: typeof FornecedorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-perfil': {
      id: '/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof MeuPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/$slug': {
      id: '/fornecedor/$slug'
      path: '/fornecedor/$slug'
      fullPath: '/fornecedor/$slug'
      preLoaderRoute: typeof FornecedorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AdminRoute,
  EntrarRoute,
  MeuPerfilRoute,
  PainelRoute,
  BuscarRoute,
  FornecedorSlugRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router'

import type { createStart } from '@tanstack/react-start'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
