/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminPerfilRouteImport } from './routes/admin-perfil'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ChatLosiRouteImport } from './routes/chat-losi'
import { Route as ColaboradorRouteImport } from './routes/colaborador'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EquipeEscalasRouteImport } from './routes/equipe-escalas'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FormulariosRouteImport } from './routes/formularios'
import { Route as LosiAdsRouteImport } from './routes/losi-ads'
import { Route as MeuPerfilRouteImport } from './routes/meu-perfil'
import { Route as MeusServicosRouteImport } from './routes/meus-servicos'
import { Route as NotificarInconsistenciaRouteImport } from './routes/notificar-inconsistencia'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PlanoDeTrabalhoRouteImport } from './routes/plano-de-trabalho'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as RecibosRouteImport } from './routes/recibos'
import { Route as RecibosRecebidosRouteImport } from './routes/recibos-recebidos'
import { Route as CalendarioTokenRouteImport } from './routes/calendario.$token'
import { Route as EmitirReciboTokenRouteImport } from './routes/emitir-recibo/$token'
import { Route as FormularioTokenRouteImport } from './routes/formulario.$token'
import { Route as FornecedorSlugRouteImport } from './routes/fornecedor/$slug'
import { Route as OportunidadeTokenRouteImport } from './routes/oportunidade.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/admin-perfil',
  path: '/admin-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatLosiRoute = ChatLosiRouteImport.update({
  id: '/chat-losi',
  path: '/chat-losi',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorRoute = ColaboradorRouteImport.update({
  id: '/colaborador',
  path: '/colaborador',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeEscalasRoute = EquipeEscalasRouteImport.update({
  id: '/equipe-escalas',
  path: '/equipe-escalas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulariosRoute = FormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => rootRouteImport,
} as any)
const LosiAdsRoute = LosiAdsRouteImport.update({
  id: '/losi-ads',
  path: '/losi-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPerfilRoute = MeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusServicosRoute = MeusServicosRouteImport.update({
  id: '/meus-servicos',
  path: '/meus-servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificarInconsistenciaRoute = NotificarInconsistenciaRouteImport.update({
  id: '/notificar-inconsistencia',
  path: '/notificar-inconsistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoDeTrabalhoRoute = PlanoDeTrabalhoRouteImport.update({
  id: '/plano-de-trabalho',
  path: '/plano-de-trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecibosRoute = RecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecibosRecebidosRoute = RecibosRecebidosRouteImport.update({
  id: '/recibos-recebidos',
  path: '/recibos-recebidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioTokenRoute = CalendarioTokenRouteImport.update({
  id: '/calendario/$token',
  path: '/calendario/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmitirReciboTokenRoute = EmitirReciboTokenRouteImport.update({
  id: '/emitir-recibo/$token',
  path: '/emitir-recibo/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioTokenRoute = FormularioTokenRouteImport.update({
  id: '/formulario/$token',
  path: '/formulario/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorSlugRoute = FornecedorSlugRouteImport.update({
  id: '/fornecedor/$slug',
  path: '/fornecedor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadeTokenRoute = OportunidadeTokenRouteImport.update({
  id: '/oportunidade/$token',
  path: '/oportunidade/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-perfil': typeof AdminPerfilRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/buscar': typeof BuscarRoute
  '/chat-losi': typeof ChatLosiRoute
  '/colaborador': typeof ColaboradorRoute
  '/entrar': typeof EntrarRoute
  '/equipe-escalas': typeof EquipeEscalasRoute
  '/faq': typeof FaqRoute
  '/feed': typeof FeedRoute
  '/formularios': typeof FormulariosRoute
  '/losi-ads': typeof LosiAdsRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/meus-servicos': typeof MeusServicosRoute
  '/notificar-inconsistencia': typeof NotificarInconsistenciaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/painel': typeof PainelRoute
  '/plano-de-trabalho': typeof PlanoDeTrabalhoRoute
  '/propostas': typeof PropostasRoute
  '/recibos': typeof RecibosRoute
  '/recibos-recebidos': typeof RecibosRecebidosRoute
  '/calendario/$token': typeof CalendarioTokenRoute
  '/emitir-recibo/$token': typeof EmitirReciboTokenRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/fornecedor/$slug': typeof FornecedorSlugRoute
  '/oportunidade/$token': typeof OportunidadeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-perfil': typeof AdminPerfilRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/buscar': typeof BuscarRoute
  '/chat-losi': typeof ChatLosiRoute
  '/colaborador': typeof ColaboradorRoute
  '/entrar': typeof EntrarRoute
  '/equipe-escalas': typeof EquipeEscalasRoute
  '/faq': typeof FaqRoute
  '/feed': typeof FeedRoute
  '/formularios': typeof FormulariosRoute
  '/losi-ads': typeof LosiAdsRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/meus-servicos': typeof MeusServicosRoute
  '/notificar-inconsistencia': typeof NotificarInconsistenciaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/painel': typeof PainelRoute
  '/plano-de-trabalho': typeof PlanoDeTrabalhoRoute
  '/propostas': typeof PropostasRoute
  '/recibos': typeof RecibosRoute
  '/recibos-recebidos': typeof RecibosRecebidosRoute
  '/calendario/$token': typeof CalendarioTokenRoute
  '/emitir-recibo/$token': typeof EmitirReciboTokenRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/fornecedor/$slug': typeof FornecedorSlugRoute
  '/oportunidade/$token': typeof OportunidadeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-perfil': typeof AdminPerfilRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/buscar': typeof BuscarRoute
  '/chat-losi': typeof ChatLosiRoute
  '/colaborador': typeof ColaboradorRoute
  '/entrar': typeof EntrarRoute
  '/equipe-escalas': typeof EquipeEscalasRoute
  '/faq': typeof FaqRoute
  '/feed': typeof FeedRoute
  '/formularios': typeof FormulariosRoute
  '/losi-ads': typeof LosiAdsRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/meus-servicos': typeof MeusServicosRoute
  '/notificar-inconsistencia': typeof NotificarInconsistenciaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/painel': typeof PainelRoute
  '/plano-de-trabalho': typeof PlanoDeTrabalhoRoute
  '/propostas': typeof PropostasRoute
  '/recibos': typeof RecibosRoute
  '/recibos-recebidos': typeof RecibosRecebidosRoute
  '/calendario/$token': typeof CalendarioTokenRoute
  '/emitir-recibo/$token': typeof EmitirReciboTokenRoute
  '/formulario/$token': typeof FormularioTokenRoute
  '/fornecedor/$slug': typeof FornecedorSlugRoute
  '/oportunidade/$token': typeof OportunidadeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-perfil'
    | '/apresentacao'
    | '/buscar'
    | '/chat-losi'
    | '/colaborador'
    | '/entrar'
    | '/equipe-escalas'
    | '/faq'
    | '/feed'
    | '/formularios'
    | '/losi-ads'
    | '/meu-perfil'
    | '/meus-servicos'
    | '/notificar-inconsistencia'
    | '/orcamentos'
    | '/painel'
    | '/plano-de-trabalho'
    | '/propostas'
    | '/recibos'
    | '/recibos-recebidos'
    | '/calendario/$token'
    | '/emitir-recibo/$token'
    | '/formulario/$token'
    | '/fornecedor/$slug'
    | '/oportunidade/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-perfil'
    | '/apresentacao'
    | '/buscar'
    | '/chat-losi'
    | '/colaborador'
    | '/entrar'
    | '/equipe-escalas'
    | '/faq'
    | '/feed'
    | '/formularios'
    | '/losi-ads'
    | '/meu-perfil'
    | '/meus-servicos'
    | '/notificar-inconsistencia'
    | '/orcamentos'
    | '/painel'
    | '/plano-de-trabalho'
    | '/propostas'
    | '/recibos'
    | '/recibos-recebidos'
    | '/calendario/$token'
    | '/emitir-recibo/$token'
    | '/formulario/$token'
    | '/fornecedor/$slug'
    | '/oportunidade/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-perfil'
    | '/apresentacao'
    | '/buscar'
    | '/chat-losi'
    | '/colaborador'
    | '/entrar'
    | '/equipe-escalas'
    | '/faq'
    | '/feed'
    | '/formularios'
    | '/losi-ads'
    | '/meu-perfil'
    | '/meus-servicos'
    | '/notificar-inconsistencia'
    | '/orcamentos'
    | '/painel'
    | '/plano-de-trabalho'
    | '/propostas'
    | '/recibos'
    | '/recibos-recebidos'
    | '/calendario/$token'
    | '/emitir-recibo/$token'
    | '/formulario/$token'
    | '/fornecedor/$slug'
    | '/oportunidade/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
  BuscarRoute: typeof BuscarRoute
  ChatLosiRoute: typeof ChatLosiRoute
  ColaboradorRoute: typeof ColaboradorRoute
  EntrarRoute: typeof EntrarRoute
  EquipeEscalasRoute: typeof EquipeEscalasRoute
  FaqRoute: typeof FaqRoute
  FeedRoute: typeof FeedRoute
  FormulariosRoute: typeof FormulariosRoute
  LosiAdsRoute: typeof LosiAdsRoute
  MeuPerfilRoute: typeof MeuPerfilRoute
  MeusServicosRoute: typeof MeusServicosRoute
  NotificarInconsistenciaRoute: typeof NotificarInconsistenciaRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PainelRoute: typeof PainelRoute
  PlanoDeTrabalhoRoute: typeof PlanoDeTrabalhoRoute
  PropostasRoute: typeof PropostasRoute
  RecibosRoute: typeof RecibosRoute
  RecibosRecebidosRoute: typeof RecibosRecebidosRoute
  CalendarioTokenRoute: typeof CalendarioTokenRoute
  EmitirReciboTokenRoute: typeof EmitirReciboTokenRoute
  FormularioTokenRoute: typeof FormularioTokenRoute
  FornecedorSlugRoute: typeof FornecedorSlugRoute
  OportunidadeTokenRoute: typeof OportunidadeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-perfil': {
      id: '/admin-perfil'
      path: '/admin-perfil'
      fullPath: '/admin-perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-losi': {
      id: '/chat-losi'
      path: '/chat-losi'
      fullPath: '/chat-losi'
      preLoaderRoute: typeof ChatLosiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador': {
      id: '/colaborador'
      path: '/colaborador'
      fullPath: '/colaborador'
      preLoaderRoute: typeof ColaboradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe-escalas': {
      id: '/equipe-escalas'
      path: '/equipe-escalas'
      fullPath: '/equipe-escalas'
      preLoaderRoute: typeof EquipeEscalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formularios': {
      id: '/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof FormulariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/losi-ads': {
      id: '/losi-ads'
      path: '/losi-ads'
      fullPath: '/losi-ads'
      preLoaderRoute: typeof LosiAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-perfil': {
      id: '/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof MeuPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-servicos': {
      id: '/meus-servicos'
      path: '/meus-servicos'
      fullPath: '/meus-servicos'
      preLoaderRoute: typeof MeusServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificar-inconsistencia': {
      id: '/notificar-inconsistencia'
      path: '/notificar-inconsistencia'
      fullPath: '/notificar-inconsistencia'
      preLoaderRoute: typeof NotificarInconsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-de-trabalho': {
      id: '/plano-de-trabalho'
      path: '/plano-de-trabalho'
      fullPath: '/plano-de-trabalho'
      preLoaderRoute: typeof PlanoDeTrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibos': {
      id: '/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof RecibosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibos-recebidos': {
      id: '/recibos-recebidos'
      path: '/recibos-recebidos'
      fullPath: '/recibos-recebidos'
      preLoaderRoute: typeof RecibosRecebidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario/$token': {
      id: '/calendario/$token'
      path: '/calendario/$token'
      fullPath: '/calendario/$token'
      preLoaderRoute: typeof CalendarioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emitir-recibo/$token': {
      id: '/emitir-recibo/$token'
      path: '/emitir-recibo/$token'
      fullPath: '/emitir-recibo/$token'
      preLoaderRoute: typeof EmitirReciboTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario/$token': {
      id: '/formulario/$token'
      path: '/formulario/$token'
      fullPath: '/formulario/$token'
      preLoaderRoute: typeof FormularioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/$slug': {
      id: '/fornecedor/$slug'
      path: '/fornecedor/$slug'
      fullPath: '/fornecedor/$slug'
      preLoaderRoute: typeof FornecedorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidade/$token': {
      id: '/oportunidade/$token'
      path: '/oportunidade/$token'
      fullPath: '/oportunidade/$token'
      preLoaderRoute: typeof OportunidadeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  ApresentacaoRoute: ApresentacaoRoute,
  BuscarRoute: BuscarRoute,
  ChatLosiRoute: ChatLosiRoute,
  ColaboradorRoute: ColaboradorRoute,
  EntrarRoute: EntrarRoute,
  EquipeEscalasRoute: EquipeEscalasRoute,
  FaqRoute: FaqRoute,
  FeedRoute: FeedRoute,
  FormulariosRoute: FormulariosRoute,
  LosiAdsRoute: LosiAdsRoute,
  MeuPerfilRoute: MeuPerfilRoute,
  MeusServicosRoute: MeusServicosRoute,
  NotificarInconsistenciaRoute: NotificarInconsistenciaRoute,
  OrcamentosRoute: OrcamentosRoute,
  PainelRoute: PainelRoute,
  PlanoDeTrabalhoRoute: PlanoDeTrabalhoRoute,
  PropostasRoute: PropostasRoute,
  RecibosRoute: RecibosRoute,
  RecibosRecebidosRoute: RecibosRecebidosRoute,
  CalendarioTokenRoute: CalendarioTokenRoute,
  EmitirReciboTokenRoute: EmitirReciboTokenRoute,
  FormularioTokenRoute: FormularioTokenRoute,
  FornecedorSlugRoute: FornecedorSlugRoute,
  OportunidadeTokenRoute: OportunidadeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
