import { readSession } from "../_shared/collaborator-sessions.ts";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};const j=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});
Deno.serve(async r=>{if(r.method==="OPTIONS")return new Response("ok",{headers:H});try{const {createClient}=await import("https://esm.sh/@supabase/supabase-js@2");const a=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const b=await r.json();const session=await readSession(a,b.sessionToken);if(!session)return j({error:"Acesse com seu ID e WhatsApp para abrir o calendário."},401);const {data:p,error:profileError}=await a.from("collaborator_profiles").select("id,losi_id,full_name,professional_name,whatsapp,city,state,photo_url").eq("id",session.profile_id).maybeSingle();if(profileError)throw profileError;if(!p)return j({error:"Acesse novamente com seu ID e WhatsApp."},401);const {error:linkError}=await a.rpc("link_collaborator_network_profile",{p_profile_id:p.id});if(linkError)throw linkError;
if(b.action==="uploadPhoto"){const raw=String(b.dataUrl||"");const m=raw.match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/);if(!m)return j({error:"Envie uma imagem JPG, PNG ou WEBP."},400);const bytes=Uint8Array.from(atob(m[2]),x=>x.charCodeAt(0));if(bytes.length>5*1024*1024)return j({error:"A foto deve ter no máximo 5 MB."},400);const ext=m[1]==="image/png"?"png":m[1]==="image/webp"?"webp":"jpg",path="collaborators/"+p.id+"/avatar."+ext;const up=await a.storage.from("profile-avatars").upload(path,bytes,{contentType:m[1],upsert:true});if(up.error)return j({error:"Não foi possível enviar a foto."},500);const {data:pub}=a.storage.from("profile-avatars").getPublicUrl(path);const photo=pub.publicUrl+"?v="+Date.now();const {error}=await a.from("collaborator_profiles").update({photo_url:photo,updated_at:new Date().toISOString()}).eq("id",p.id);if(error)return j({error:"Não foi possível salvar a foto."},500);return j({success:true,photo_url:photo})}
if(b.action==="updateProfile"){const patch:any={updated_at:new Date().toISOString()};for(const k of ["full_name","professional_name","city","state"]){if(k in b)patch[k]=String(b[k]||"").trim()||null}if(!patch.full_name&&"full_name" in patch)return j({error:"Nome completo é obrigatório."},400);const {data:u,error}=await a.from("collaborator_profiles").update(patch).eq("id",p.id).select("id,losi_id,full_name,professional_name,whatsapp,city,state,photo_url").single();if(error)return j({error:"Não foi possível atualizar seu perfil."},500);await a.from("team_collaborators").update({name:u.full_name,city:u.city,state:u.state,updated_at:new Date().toISOString()}).eq("profile_id",p.id);return j({success:true,collaborator:{...u,name:u.full_name}})}
const {data:links}=await a.from("team_collaborators").select("id,business_id,network_status,business_profiles(business_name)").eq("profile_id",p.id);const linkedIds=(links||[]).map((x:any)=>x.id);if(linkedIds.length){const {error:historyError}=await a.from("team_applications").update({profile_id:p.id}).in("collaborator_id",linkedIds).is("profile_id",null);if(historyError)throw historyError}const active=(links||[]).filter((x:any)=>x.network_status==="active");
// Roster visibility is scoped to an event in which the current collaborator participates.
if(b.action==="eventDetails"){
 const eventId=String(b.eventId||"");
 const {data:membership,error:membershipError}=await a.from("team_applications").select("id").eq("event_id",eventId).eq("profile_id",p.id).in("status",["pending","approved","confirmed"]).limit(1).maybeSingle();
 if(membershipError)throw membershipError;if(!membership)return j({error:"Este evento não faz parte das suas participações ativas."},404);
 const {data:event,error:eventError}=await a.from("team_events").select("title,description,event_date,starts_at,ends_at,location_name,address,city,state,business_profiles(business_name),team_event_openings(title)").eq("id",eventId).maybeSingle();
 if(eventError)throw eventError;if(!event)return j({error:"Evento não encontrado."},404);
 const {data:rows,error:rosterError}=await a.from("team_applications").select("candidate_name,attendance_status,collaborator_profiles(full_name,professional_name,photo_url),team_collaborators!team_applications_collaborator_id_fkey(name,collaborator_profiles(full_name,professional_name,photo_url))").eq("event_id",eventId).eq("status","confirmed").order("candidate_name");
 if(rosterError)throw rosterError;
 const one=(value:any)=>Array.isArray(value)?value[0]:value;
 const escalados=(rows||[]).filter((row:any)=>row.attendance_status!=="unavailable").map((row:any)=>{const profile=one(row.collaborator_profiles)||one(one(row.team_collaborators)?.collaborator_profiles);return {name:profile?.professional_name||profile?.full_name||one(row.team_collaborators)?.name||row.candidate_name||"Colaborador",photo_url:profile?.photo_url||null}});
 // Explicit allowlist: no IDs, phones, pay, roles or underlying profile objects leave this endpoint.
 return j({event:{title:event.title,description:event.description,event_date:event.event_date,starts_at:event.starts_at,ends_at:event.ends_at,location_name:event.location_name,address:event.address,city:event.city,state:event.state,business_name:one(event.business_profiles)?.business_name||"Fornecedor LOSI",vacancies:(event.team_event_openings||[]).map((o:any)=>o.title)},escalados});
}
if(b.action==="readNotification"){const id=String(b.notificationId||"");const {error}=await a.from("collaborator_notifications").update({read_at:new Date().toISOString()}).eq("id",id).eq("profile_id",p.id);if(error)return j({error:"Não foi possível atualizar a notificação."},500);return j({success:true})}
if(b.action==="respond"){const id=String(b.applicationId||""),response=String(b.response||"");if(!["confirmed","unavailable"].includes(response))return j({error:"Resposta inválida."},400);const {data:x}=await a.from("team_applications").select("id").eq("id",id).eq("profile_id",p.id).eq("status","confirmed").maybeSingle();if(!x)return j({error:"Escala não encontrada."},404);const {error}=await a.from("team_applications").update({attendance_status:response,attendance_responded_at:new Date().toISOString()}).eq("id",id);if(error)return j({error:error.code==="23514"&&error.message?.startsWith("Conflito de horários:")?error.message:"Não foi possível registrar sua resposta."},error.code==="23514"?409:500);return j({success:true,response})}
const {data:items}=await a.from("team_applications").select("id,status,assigned_role,agreed_value,attendance_status,attendance_responded_at,removed_from_scale_at,removal_reason,team_events(id,title,status,event_date,starts_at,ends_at,location_name,address,city,state,business_id,business_profiles(business_name)),team_event_openings(title)").eq("profile_id",p.id).in("status",["pending","approved","confirmed","rejected","removed","withdrawn"]).order("created_at",{ascending:false});const {data:events,error:eventsError}=await a.from("team_events").select("id,title,description,event_date,starts_at,location_name,city,state,business_id,public_token,business_profiles(business_name),team_event_openings(id,title,slots)").eq("status","open").gte("event_date",new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())).order("event_date",{ascending:true});if(eventsError)throw eventsError;const joined=new Set((items||[]).map((x:any)=>x.team_events?.id));const opportunities=(events||[]).filter((e:any)=>e.public_token&&e.team_event_openings?.some((opening:any)=>Number(opening.slots)>0)&&!joined.has(e.id));const {data:notifications}=await a.from("collaborator_notifications").select("id,type,title,message,event_id,application_id,action_url,read_at,created_at").eq("profile_id",p.id).order("created_at",{ascending:false}).limit(30);return j({collaborator:{...p,name:p.full_name},networks:active,items:items||[],opportunities,notifications:notifications||[]})}catch(e){console.error(e);return j({error:"Erro interno."},500)}});
